'use client'
import { createContext, useContext, useEffect, useState } from 'react'

type Lang = 'fr' | 'en'

const translations = {
  fr: {
    // Navbar
    nav_annuaire: 'Annuaire',
    nav_teams: 'Teams',
    nav_trades: 'Trades',
    nav_recherche: '🔍 Recherche',
    nav_tuto: 'Tutoriel',
    nav_galerie: 'Ma galerie',
    nav_messages: 'Messages',
    nav_profil: 'Profil',
    nav_connexion: 'Connexion',
    nav_inscription: "S'inscrire",
    nav_deconnexion: 'Déconnexion',
    nav_mode_clair: '☀️ Mode clair',
    nav_mode_sombre: '🌙 Mode sombre',

    // Accueil
    home_hero: 'Exposez votre passion en 3D.',
    home_sub: 'La plateforme ultime pour les collectionneurs de cartes de Sports.',
    home_cta1: 'Créer ma galerie',
    home_cta2: "Voir l'annuaire",
    home_collectors: 'Collectionneurs',
    home_cards: 'Cartes répertoriées',
    home_3d: '100% Interactif & 3D',
    home_pepites: '✨ Dernières pépites',

    // Galerie
    gallery_search: 'Joueur, variation...',
    gallery_team: 'Équipe',
    gallery_all: 'Toutes',
    gallery_collection: 'Collection',
    gallery_year: 'Année',
    gallery_privacy: 'Gérer les cartes',
    gallery_done: '✓ Terminer',
    gallery_message: '💬 Envoyer un message',
    gallery_share: '🔗 Partager',
    gallery_private: '🔒 PRIVÉ',
    gallery_make_private: '🔒 Rendre privé',
    gallery_make_public: '🔓 Rendre public',
    gallery_total: 'carte(s) au total',

    // Trades
    trades_title: 'Trades',
    trades_post: '+ Poster une annonce',
    trades_search: 'Rechercher un joueur, une carte...',
    trades_all: 'Tous',
    trades_sport_label: 'Sport :',
    trades_offers: '📤 Offres',
    trades_searches: '📥 Recherches',
    trades_sport: 'Sport :',
    trades_tags: 'Tags :',
    trades_by: 'Proposé par',
    trades_mark_done: '✓ Marquer comme conclu',
    trades_edit: '✏️ Modifier l\'annonce',
    trades_delete: '🗑️ Supprimer l\'annonce',
    trades_published: 'Publié le',

    // Annuaire
    directory_title: 'Annuaire des collectionneurs',
    directory_collector: 'Collectionneur',
    directory_total: 'Total',

    // Teams
    teams_title: 'Annuaire des Teams',
    teams_create: 'Créer ma Team',
    teams_search: 'Rechercher une team...',
    teams_members: 'Membres',
    teams_total_cards: 'Total cartes',
    teams_action: 'Action',
    teams_join: 'Rejoindre',
    teams_pending: '⏳ En attente',
    teams_my_team: 'Ma Team ✓',
    teams_chat: '💬 Chat',
    teams_candidatures: '📋 Candidatures',
    teams_no_message: 'Aucun message — soyez le premier à écrire !',
    teams_send: 'Envoyer',
    teams_accept: '✓ Accepter',
    teams_refuse: '✗ Refuser',
    teams_promote: '↑ Promouvoir',
    teams_demote: '↓ Rétrograder',
    teams_kick: '🚫 Kick',
    teams_leave: 'Quitter la team',
    teams_modify: '✏️ Modifier',
    teams_no_candidatures: 'Aucune candidature en attente',

    // Profil
    profile_title: 'Mon profil',
    profile_save: 'Sauvegarder',
    profile_saved: '✓ Sauvegardé !',
    profile_pseudo: 'Pseudo',
    profile_csv: 'Lien CSV Google Sheets',
    profile_logo: 'URL de votre logo',
    profile_border: 'Couleur des bordures',
    profile_danger: '⚠️ Zone de danger',
    profile_delete: 'Supprimer mon compte',
    profile_delete_confirm: 'Tapez SUPPRIMER pour confirmer :',
    profile_delete_btn: 'Supprimer définitivement',
    profile_cancel: 'Annuler',
    profile_photo: 'Photo de profil',
    profile_change_photo: '📷 Changer ma photo',

    // Messages
    messages_title: 'Messages',
    messages_none: 'Aucune conversation',
    messages_select: 'Sélectionnez une conversation',
    messages_placeholder: 'Votre message...',
    messages_send: 'Envoyer',

    // Notifications
    notif_title: '🔔 Notifications',
    notif_none: 'Aucune notification pour l\'instant',

    // Auth
    login_title: 'Connexion',
    login_email: 'Email',
    login_password: 'Mot de passe',
    login_btn: 'Se connecter',
    login_no_account: 'Pas encore de compte ?',
    login_forgot: 'Mot de passe oublié ?',
    register_title: 'Créer un compte',
    register_sub: 'Rejoignez la communauté des collectionneurs',
    register_pseudo: 'Pseudo',
    register_btn: 'Créer mon compte',
    register_have_account: 'Déjà un compte ?',
    register_connect: 'Se connecter',

    // 404
    not_found_title: 'Cette carte n\'existe pas',
    not_found_sub: 'La page que vous cherchez n\'existe pas ou a été déplacée.',
    not_found_home: 'Retour à l\'accueil',
    not_found_directory: 'Voir l\'annuaire',

    // Extras
    gallery_cards: 'Cartes',
    gallery_search_label: 'Recherche',
    gallery_team_label: 'Équipe',
    gallery_collection_label: 'Collection',
    gallery_year_label: 'Année',
    by_label: 'par',
    all_teams: 'Toutes les teams',
    directory_back_all_teams: '← Toutes les teams',
    directory_all_nba: '🏀 Toutes les équipes NBA',
    directory_search_placeholder: 'Rechercher un collectionneur…',
    teams_role: 'Rôle',
    teams_cards: 'Cartes',
    teams_collector: 'Collectionneur',
    teams_total_cards_label: 'Total cartes',
    teams_see_my_team: 'Voir ma team →',
    profile_csv_label: 'Lien CSV Google Sheets',
    profile_logo_label: 'URL de votre logo (galerie)',
    profile_delete_warning: 'La suppression de votre compte est irréversible. Toutes vos données seront perdues.',
    pwa_install: 'Installer Memorabilius',
    pwa_sub: 'Accès rapide depuis votre écran d\'accueil',
    pwa_later: 'Plus tard',
    pwa_install_btn: 'Installer',
    search_title: '🔍 Recherche globale',
    search_sub: 'Cherchez une carte dans toutes les collections de la communauté',
    search_placeholder: 'Nom du joueur, équipe, variation...',
    search_min_chars: 'Tapez au moins 2 caractères',
    search_results: 'carte(s) trouvée(s) pour',
    search_none: 'Aucune carte trouvée pour',
    search_none_sub: 'Essayez avec un nom différent ou vérifiez l\'orthographe',
    tuto_video: '🎬 Tutoriel Vidéo',
    tuto_title: 'Comment créer votre galerie',
    tuto_sub: 'Suivez ces 4 étapes simples pour lier votre collection Google Sheets à Memorabilius.',

    // Profil - extras
    profile_fav_teams: 'Équipes favorites (max 5)',
    profile_wrap_before: 'Recevoir le ',
    profile_wrap_name: 'Wrap mensuel',
    profile_wrap_after: ' par email (résumé de ta collection chaque 1er du mois)',
    profile_password: 'Mot de passe',
    profile_password_change: 'Modifier le mot de passe',
    profile_password_new: 'Nouveau mot de passe',
    profile_password_confirm: 'Confirmer le mot de passe',
    profile_password_min: 'Min. 8 caractères',
    profile_password_repeat: 'Répéter le mot de passe',
    profile_password_saving: 'En cours...',
    profile_password_save: 'Enregistrer',
    profile_password_mismatch: 'Les mots de passe ne correspondent pas.',
    profile_password_tooshort: 'Le mot de passe doit faire au moins 8 caractères.',
    profile_password_success: 'Mot de passe modifié avec succès !',
    profile_status_label: 'Statut :',
    profile_status_synced: 'Collection synchronisée 🟢',
    profile_status_none: 'Aucune collection liée 🔴',
    profile_status_hint: 'Ajoutez votre lien CSV ci-dessous pour activer votre galerie.',
    profile_view_gallery: 'Voir ma galerie →',
    profile_uploading: 'Upload en cours...',
    profile_bio_label: 'Bio',
    profile_bio_placeholder: 'Décrivez votre collection en quelques mots...',
    profile_bio_chars: 'caractères',
    profile_csv_hint: 'Fichier > Partager > Publier sur le web > CSV',

    // Setlist
    setlist_collections_available: 'collections disponibles',
    setlist_sync_btn: '🔄 Synchroniser ma galerie',
    setlist_syncing: 'Synchronisation...',
    setlist_new_match_one: 'nouvelle carte cochée',
    setlist_new_match_other: 'nouvelles cartes cochées',
    setlist_cards_synced: 'cartes synchronisées',
    setlist_in: 'dans',
    setlist_see_unplaced: 'Voir les cartes non placées',
    setlist_unplaced_title: 'Cartes non placées dans un setlist',
    setlist_sync_first: "Lance une synchronisation pour voir quelles cartes de ta galerie ne sont pas dans un setlist.",
    setlist_all_placed: 'Toutes tes cartes sont placées dans un setlist 🎉',
    setlist_card_no_match: 'carte sans correspondance. Choisis un setlist pour la placer.',
    setlist_cards_no_match: 'cartes sans correspondance. Choisis un setlist pour les placer.',
    setlist_add_manual: '+ Ajouter une carte manuellement',
    setlist_player: 'Joueur *',
    setlist_year_ex: 'Année (ex: 2024-25)',
    setlist_brand: 'Marque',
    setlist_add: 'Ajouter',
    setlist_placing: 'Placement...',
    setlist_place_in: 'Placer dans…',
    setlist_other: 'Autre',
    setlist_choose_set: 'Choisir un set…',
    setlist_filtered: 'Filtrés',
    setlist_all_sets: 'Tous',
    setlist_see_set: 'Voir le set',
    setlist_done: '✓ Fait',
    setlist_season: 'Saison',
    setlist_completed: 'complété',
    setlist_loading: 'Chargement...',
    setlist_no_collection: 'Aucune collection pour cette saison.',
    setlist_cards: 'cartes',
    setlist_owned: 'possédées',

    // Events
    events_sub: 'Card shows, conventions et rencontres de collectionneurs',
    events_propose_btn: '+ Proposer un événement',
    events_loading: 'Chargement...',
    events_none: 'Aucun événement pour le moment.',
    events_propose_first: 'Proposer le premier',
    events_upcoming: 'À venir',
    events_past: 'Passés',
    events_propose_title: 'Proposer un événement',
    events_submitted: "Demande envoyée ! Les admins vont l'examiner.",
    events_event_name: "Nom de l'événement *",
    events_description: 'Description (optionnel)',
    events_city: 'Ville *',
    events_country: 'Pays',
    events_location: 'Lieu (ex: Parc des Expositions)',
    events_website: 'Site web (optionnel)',
    events_uploading: 'Upload...',
    events_add_image: '🖼️ Ajouter une image (optionnel)',
    events_submitting: 'Envoi...',
    events_send: 'Envoyer la demande',
    events_official_site: '🔗 Site officiel',
    events_going: "✅ J'y vais",
    events_going_q: "📌 J'y vais ?",
    events_attendee_one: 'participant',
    events_attendee_other: 'participants',
  },
  en: {
    // Navbar
    nav_annuaire: 'Directory',
    nav_teams: 'Teams',
    nav_trades: 'Trades',
    nav_recherche: '🔍 Search',
    nav_tuto: 'Tutorial',
    nav_galerie: 'My gallery',
    nav_messages: 'Messages',
    nav_profil: 'Profile',
    nav_connexion: 'Login',
    nav_inscription: 'Sign up',
    nav_deconnexion: 'Logout',
    nav_mode_clair: '☀️ Light mode',
    nav_mode_sombre: '🌙 Dark mode',

    // Home
    home_hero: 'Showcase your passion in 3D.',
    home_sub: 'The ultimate platform for sports card collectors.',
    home_cta1: 'Create my gallery',
    home_cta2: 'View directory',
    home_collectors: 'Collectors',
    home_cards: 'Cards listed',
    home_3d: '100% Interactive & 3D',
    home_pepites: '✨ Latest gems',

    // Gallery
    gallery_search: 'Player, variation...',
    gallery_team: 'Team',
    gallery_all: 'All',
    gallery_collection: 'Collection',
    gallery_year: 'Year',
    gallery_privacy: 'Manage cards',
    gallery_done: '✓ Done',
    gallery_message: '💬 Send a message',
    gallery_share: '🔗 Share',
    gallery_private: '🔒 PRIVATE',
    gallery_make_private: '🔒 Make private',
    gallery_make_public: '🔓 Make public',
    gallery_total: 'card(s) total',

    // Trades
    trades_title: 'Trades',
    trades_post: '+ Post an ad',
    trades_search: 'Search a player, card...',
    trades_all: 'All',
    trades_sport_label: 'Sport:',
    trades_offers: '📤 Offers',
    trades_searches: '📥 Searches',
    trades_sport: 'Sport:',
    trades_tags: 'Tags:',
    trades_by: 'Posted by',
    trades_mark_done: '✓ Mark as completed',
    trades_edit: '✏️ Edit ad',
    trades_delete: '🗑️ Delete ad',
    trades_published: 'Published on',

    // Directory
    directory_title: 'Collectors directory',
    directory_collector: 'Collector',
    directory_total: 'Total',

    // Teams
    teams_title: 'Teams directory',
    teams_create: 'Create my Team',
    teams_search: 'Search a team...',
    teams_members: 'Members',
    teams_total_cards: 'Total cards',
    teams_action: 'Action',
    teams_join: 'Join',
    teams_pending: '⏳ Pending',
    teams_my_team: 'My Team ✓',
    teams_chat: '💬 Chat',
    teams_candidatures: '📋 Applications',
    teams_no_message: 'No messages yet — be the first to write!',
    teams_send: 'Send',
    teams_accept: '✓ Accept',
    teams_refuse: '✗ Decline',
    teams_promote: '↑ Promote',
    teams_demote: '↓ Demote',
    teams_kick: '🚫 Kick',
    teams_leave: 'Leave team',
    teams_modify: '✏️ Edit',
    teams_no_candidatures: 'No pending applications',

    // Profile
    profile_title: 'My profile',
    profile_save: 'Save',
    profile_saved: '✓ Saved!',
    profile_pseudo: 'Username',
    profile_csv: 'Google Sheets CSV link',
    profile_logo: 'Your logo URL',
    profile_border: 'Border color',
    profile_danger: '⚠️ Danger zone',
    profile_delete: 'Delete my account',
    profile_delete_confirm: 'Type DELETE to confirm:',
    profile_delete_btn: 'Delete permanently',
    profile_cancel: 'Cancel',
    profile_photo: 'Profile picture',
    profile_change_photo: '📷 Change my photo',

    // Messages
    messages_title: 'Messages',
    messages_none: 'No conversations',
    messages_select: 'Select a conversation',
    messages_placeholder: 'Your message...',
    messages_send: 'Send',

    // Notifications
    notif_title: '🔔 Notifications',
    notif_none: 'No notifications yet',

    // Auth
    login_title: 'Login',
    login_email: 'Email',
    login_password: 'Password',
    login_btn: 'Sign in',
    login_no_account: 'No account yet?',
    login_forgot: 'Forgot password?',
    register_title: 'Create an account',
    register_sub: 'Join the collectors community',
    register_pseudo: 'Username',
    register_btn: 'Create my account',
    register_have_account: 'Already have an account?',
    register_connect: 'Sign in',

    // 404
    not_found_title: 'This card does not exist',
    not_found_sub: 'The page you are looking for does not exist or has been moved.',
    not_found_home: 'Back to home',
    not_found_directory: 'View directory',

    // Extras
    gallery_cards: 'Cards',
    gallery_search_label: 'Search',
    gallery_team_label: 'Team',
    gallery_collection_label: 'Collection',
    gallery_year_label: 'Year',
    by_label: 'by',
    all_teams: 'All teams',
    directory_back_all_teams: '← All teams',
    directory_all_nba: '🏀 All NBA teams',
    directory_search_placeholder: 'Search collector…',
    teams_role: 'Role',
    teams_cards: 'Cards',
    teams_collector: 'Collector',
    teams_total_cards_label: 'Total cards',
    teams_see_my_team: 'View my team →',
    profile_csv_label: 'Google Sheets CSV link',
    profile_logo_label: 'Your logo URL (gallery)',
    profile_delete_warning: 'Account deletion is irreversible. All your data will be lost.',
    pwa_install: 'Install Memorabilius',
    pwa_sub: 'Quick access from your home screen',
    pwa_later: 'Later',
    pwa_install_btn: 'Install',
    search_title: '🔍 Global search',
    search_sub: 'Search for a card across all community collections',
    search_placeholder: 'Player name, team, variant...',
    search_min_chars: 'Type at least 2 characters',
    search_results: 'card(s) found for',
    search_none: 'No cards found for',
    search_none_sub: 'Try a different name or check the spelling',
    tuto_video: '🎬 Video Tutorial',
    tuto_title: 'How to create your gallery',
    tuto_sub: 'Follow these 4 simple steps to link your Google Sheets collection to Memorabilius.',

    // Profile - extras
    profile_fav_teams: 'Favorite teams (max 5)',
    profile_wrap_before: 'Receive the ',
    profile_wrap_name: 'Monthly Wrap',
    profile_wrap_after: ' by email (a summary of your collection every 1st of the month)',
    profile_password: 'Password',
    profile_password_change: 'Change password',
    profile_password_new: 'New password',
    profile_password_confirm: 'Confirm password',
    profile_password_min: 'Min. 8 characters',
    profile_password_repeat: 'Repeat password',
    profile_password_saving: 'Saving...',
    profile_password_save: 'Save',
    profile_password_mismatch: 'Passwords do not match.',
    profile_password_tooshort: 'Password must be at least 8 characters.',
    profile_password_success: 'Password changed successfully!',
    profile_status_label: 'Status:',
    profile_status_synced: 'Collection synced 🟢',
    profile_status_none: 'No collection linked 🔴',
    profile_status_hint: 'Add your CSV link below to activate your gallery.',
    profile_view_gallery: 'View my gallery →',
    profile_uploading: 'Uploading...',
    profile_bio_label: 'Bio',
    profile_bio_placeholder: 'Describe your collection in a few words...',
    profile_bio_chars: 'characters',
    profile_csv_hint: 'File > Share > Publish to web > CSV',

    // Setlist
    setlist_collections_available: 'collections available',
    setlist_sync_btn: '🔄 Sync my gallery',
    setlist_syncing: 'Syncing...',
    setlist_new_match_one: 'new card checked',
    setlist_new_match_other: 'new cards checked',
    setlist_cards_synced: 'cards synced',
    setlist_in: 'in',
    setlist_see_unplaced: 'View unplaced cards',
    setlist_unplaced_title: 'Cards not placed in a setlist',
    setlist_sync_first: 'Run a sync to see which cards in your gallery are not in a setlist.',
    setlist_all_placed: 'All your cards are placed in a setlist 🎉',
    setlist_card_no_match: 'card without a match. Choose a setlist to place it.',
    setlist_cards_no_match: 'cards without a match. Choose a setlist to place them.',
    setlist_add_manual: '+ Add a card manually',
    setlist_player: 'Player *',
    setlist_year_ex: 'Year (ex: 2024-25)',
    setlist_brand: 'Brand',
    setlist_add: 'Add',
    setlist_placing: 'Placing...',
    setlist_place_in: 'Place in…',
    setlist_other: 'Other',
    setlist_choose_set: 'Choose a set…',
    setlist_filtered: 'Filtered',
    setlist_all_sets: 'All',
    setlist_see_set: 'View set',
    setlist_done: '✓ Done',
    setlist_season: 'Season',
    setlist_completed: 'complete',
    setlist_loading: 'Loading...',
    setlist_no_collection: 'No collection for this season.',
    setlist_cards: 'cards',
    setlist_owned: 'owned',

    // Events
    events_sub: 'Card shows, conventions and collector meetups',
    events_propose_btn: '+ Propose an event',
    events_loading: 'Loading...',
    events_none: 'No events yet.',
    events_propose_first: 'Be the first',
    events_upcoming: 'Upcoming',
    events_past: 'Past',
    events_propose_title: 'Propose an event',
    events_submitted: 'Request sent! Admins will review it.',
    events_event_name: 'Event name *',
    events_description: 'Description (optional)',
    events_city: 'City *',
    events_country: 'Country',
    events_location: 'Venue (e.g., Convention Center)',
    events_website: 'Website (optional)',
    events_uploading: 'Uploading...',
    events_add_image: '🖼️ Add an image (optional)',
    events_submitting: 'Sending...',
    events_send: 'Send request',
    events_official_site: '🔗 Official website',
    events_going: '✅ Going',
    events_going_q: '📌 Going?',
    events_attendee_one: 'attendee',
    events_attendee_other: 'attendees',
  }
}

type TranslationKey = keyof typeof translations.fr

const LangContext = createContext<{
  lang: Lang
  setLang: (l: Lang) => void
  t: (key: TranslationKey) => string
}>({ lang: 'fr', setLang: () => {}, t: (k) => k })

export function LangProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>('fr')

  useEffect(() => {
    const saved = localStorage.getItem('lang') as Lang
    if (saved === 'fr' || saved === 'en') setLangState(saved)
    else {
      // Détecter la langue du navigateur
      const browser = navigator.language.startsWith('en') ? 'en' : 'fr'
      setLangState(browser)
    }
  }, [])

  const setLang = (l: Lang) => {
    setLangState(l)
    localStorage.setItem('lang', l)
  }

  const t = (key: TranslationKey): string => translations[lang][key] || translations.fr[key] || key

  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  )
}

export const useLang = () => useContext(LangContext)
