'use client'
import { createContext, useContext, useEffect, useState } from 'react'

type Lang = 'fr' | 'en' | 'de'

const translations = {
  fr: {
    // Navbar
    nav_communaute: 'Communauté',
    nav_outils: 'Outils',
    nav_evenements: 'Événements',
    nav_scanner: 'Scanner de prix',
    nav_setlist: 'Setlist',
    nav_admin_stats: 'Stats admin',
    nav_my_account: 'Mon compte',
    nav_annuaire: 'Annuaire',
    nav_teams: 'Teams',
    nav_trades: 'Trades',
    nav_recherche: '🔍 Recherche',
    nav_tuto: 'Tutoriel',
    nav_galerie: 'Ma galerie',
    nav_messages: 'Messages',
    nav_profil: 'Profil',
    nav_connexion: 'Connexion',
    nav_inscription: "S'inscrire",
    nav_deconnexion: 'Déconnexion',
    nav_mode_clair: '☀️ Mode clair',
    nav_mode_sombre: '🌙 Mode sombre',

    // Accueil
    home_hero: 'Collectionnez. Identifiez. Échangez.',
    home_sub: "Galerie 3D interactive, scan IA, prix eBay en direct et système d'échanges — la plateforme complète pour les passionnés de cartes.",
    home_cta1: 'Créer ma galerie',
    home_cta2: "Voir l'annuaire",
    home_collectors: 'Collectionneurs',
    home_cards: 'Cartes répertoriées',
    home_binders: 'Classeurs partagés',
    home_trade: 'Cartes à échanger / vendre',
    home_pepites: '✨ Dernières pépites',

    // Galerie
    gallery_search: 'Joueur, variation...',
    gallery_team: 'Équipe',
    gallery_all: 'Toutes',
    gallery_collection: 'Collection',
    gallery_year: 'Année',
    gallery_privacy: 'Gérer les cartes',
    gallery_done: '✓ Terminer',
    gallery_message: '💬 Envoyer un message',
    gallery_share: '🔗 Partager',
    gallery_private: '🔒 PRIVÉ',
    gallery_make_private: '🔒 Rendre privé',
    gallery_make_public: '🔓 Rendre public',
    gallery_total: 'carte(s) au total',

    // Trades
    trades_title: 'Trades',
    trades_post: '+ Poster une annonce',
    trades_search: 'Rechercher un joueur, une carte...',
    trades_all: 'Tous',
    trades_sport_label: 'Sport :',
    trades_offers: '📤 Offres',
    trades_searches: '📥 Recherches',
    trades_sport: 'Sport :',
    trades_tags: 'Tags :',
    trades_by: 'Proposé par',
    trades_mark_done: '✓ Marquer comme conclu',
    trades_edit: '✏️ Modifier l\'annonce',
    trades_delete: '🗑️ Supprimer l\'annonce',
    trades_published: 'Publié le',

    // Annuaire
    directory_title: 'Annuaire des collectionneurs',
    directory_collector: 'Collectionneur',
    directory_total: 'Total',

    // Teams
    teams_title: 'Annuaire des Teams',
    teams_create: 'Créer ma Team',
    teams_search: 'Rechercher une team...',
    teams_members: 'Membres',
    teams_total_cards: 'Total cartes',
    teams_action: 'Action',
    teams_join: 'Rejoindre',
    teams_pending: '⏳ En attente',
    teams_my_team: 'Ma Team ✓',
    teams_chat: '💬 Chat',
    teams_candidatures: '📋 Candidatures',
    teams_no_message: 'Aucun message — soyez le premier à écrire !',
    teams_send: 'Envoyer',
    teams_accept: '✓ Accepter',
    teams_refuse: '✗ Refuser',
    teams_promote: '↑ Promouvoir',
    teams_demote: '↓ Rétrograder',
    teams_kick: '🚫 Kick',
    teams_leave: 'Quitter la team',
    teams_modify: '✏️ Modifier',
    teams_no_candidatures: 'Aucune candidature en attente',

    // Profil
    profile_title: 'Mon profil',
    profile_save: 'Sauvegarder',
    profile_saved: '✓ Sauvegardé !',
    profile_pseudo: 'Pseudo',
    profile_csv: 'Lien CSV Google Sheets',
    profile_logo: 'URL de votre logo',
    profile_border: 'Couleur des bordures',
    profile_danger: '⚠️ Zone de danger',
    profile_delete: 'Supprimer mon compte',
    profile_delete_confirm: 'Tapez SUPPRIMER pour confirmer :',
    profile_delete_btn: 'Supprimer définitivement',
    profile_cancel: 'Annuler',
    profile_photo: 'Photo de profil',
    profile_change_photo: '📷 Changer ma photo',

    // Messages
    messages_title: 'Messages',
    messages_none: 'Aucune conversation',
    messages_select: 'Sélectionnez une conversation',
    messages_placeholder: 'Votre message...',
    messages_send: 'Envoyer',

    // Notifications
    notif_title: '🔔 Notifications',
    notif_none: 'Aucune notification pour l\'instant',

    // Auth
    login_title: 'Connexion',
    login_email: 'Email',
    login_password: 'Mot de passe',
    login_btn: 'Se connecter',
    login_no_account: 'Pas encore de compte ?',
    login_forgot: 'Mot de passe oublié ?',
    register_title: 'Créer un compte',
    register_sub: 'Rejoignez la communauté des collectionneurs',
    register_pseudo: 'Pseudo',
    register_btn: 'Créer mon compte',
    register_have_account: 'Déjà un compte ?',
    register_connect: 'Se connecter',

    // 404
    not_found_title: 'Cette carte n\'existe pas',
    not_found_sub: 'La page que vous cherchez n\'existe pas ou a été déplacée.',
    not_found_home: 'Retour à l\'accueil',
    not_found_directory: 'Voir l\'annuaire',

    // Extras
    gallery_cards: 'Cartes',
    gallery_search_label: 'Recherche',
    gallery_team_label: 'Équipe',
    gallery_collection_label: 'Collection',
    gallery_year_label: 'Année',
    by_label: 'par',
    all_teams: 'Toutes les teams',
    directory_back_all_teams: '← Toutes les teams',
    directory_all_nba: '🏀 Toutes les équipes NBA',
    directory_search_placeholder: 'Rechercher un collectionneur…',
    teams_role: 'Rôle',
    teams_cards: 'Cartes',
    teams_collector: 'Collectionneur',
    teams_total_cards_label: 'Total cartes',
    teams_see_my_team: 'Voir ma team →',
    profile_csv_label: 'Lien CSV Google Sheets',
    profile_logo_label: 'URL de votre logo (galerie)',
    profile_delete_warning: 'La suppression de votre compte est irréversible. Toutes vos données seront perdues.',
    pwa_install: 'Installer Memorabilius',
    pwa_sub: 'Accès rapide depuis votre écran d\'accueil',
    pwa_later: 'Plus tard',
    pwa_install_btn: 'Installer',
    search_title: '🔍 Recherche globale',
    search_sub: 'Cherchez une carte dans toutes les collections de la communauté',
    search_placeholder: 'Nom du joueur, équipe, variation...',
    search_min_chars: 'Tapez au moins 2 caractères',
    search_results: 'carte(s) trouvée(s) pour',
    search_none: 'Aucune carte trouvée pour',
    search_none_sub: 'Essayez avec un nom différent ou vérifiez l\'orthographe',
    tuto_video: '🎬 Tutoriel Vidéo',
    tuto_title: 'Comment créer votre galerie',
    tuto_sub: 'Suivez ces 4 étapes simples pour lier votre collection Google Sheets à Memorabilius.',

    // Profil - extras
    profile_fav_teams: 'Équipes favorites (max 5)',
    profile_wrap_before: 'Recevoir le ',
    profile_wrap_name: 'Wrap mensuel',
    profile_wrap_after: ' par email (résumé de ta collection chaque 1er du mois)',
    profile_password: 'Mot de passe',
    profile_password_change: 'Modifier le mot de passe',
    profile_password_new: 'Nouveau mot de passe',
    profile_password_confirm: 'Confirmer le mot de passe',
    profile_password_min: 'Min. 8 caractères',
    profile_password_repeat: 'Répéter le mot de passe',
    profile_password_saving: 'En cours...',
    profile_password_save: 'Enregistrer',
    profile_password_mismatch: 'Les mots de passe ne correspondent pas.',
    profile_password_tooshort: 'Le mot de passe doit faire au moins 8 caractères.',
    profile_password_success: 'Mot de passe modifié avec succès !',
    profile_status_label: 'Statut :',
    profile_status_synced: 'Collection synchronisée 🟢',
    profile_status_none: 'Aucune collection liée 🔴',
    profile_status_hint: 'Ajoutez votre lien CSV ci-dessous pour activer votre galerie.',
    profile_view_gallery: 'Voir ma galerie →',
    profile_uploading: 'Upload en cours...',
    profile_bio_label: 'Bio',
    profile_bio_placeholder: 'Décrivez votre collection en quelques mots...',
    profile_bio_chars: 'caractères',
    profile_csv_hint: 'Fichier > Partager > Publier sur le web > CSV',

    // Setlist
    setlist_collections_available: 'collections disponibles',
    setlist_sync_btn: '🔄 Synchroniser ma galerie',
    setlist_syncing: 'Synchronisation...',
    setlist_new_match_one: 'nouvelle carte cochée',
    setlist_new_match_other: 'nouvelles cartes cochées',
    setlist_cards_synced: 'cartes synchronisées',
    setlist_in: 'dans',
    setlist_see_unplaced: 'Voir les cartes non placées',
    setlist_unplaced_title: 'Cartes non placées dans un setlist',
    setlist_sync_first: "Lance une synchronisation pour voir quelles cartes de ta galerie ne sont pas dans un setlist.",
    setlist_all_placed: 'Toutes tes cartes sont placées dans un setlist 🎉',
    setlist_card_no_match: 'carte sans correspondance. Choisis un setlist pour la placer.',
    setlist_cards_no_match: 'cartes sans correspondance. Choisis un setlist pour les placer.',
    setlist_add_manual: '+ Ajouter une carte manuellement',
    setlist_player: 'Joueur *',
    setlist_year_ex: 'Année (ex: 2024-25)',
    setlist_brand: 'Marque',
    setlist_add: 'Ajouter',
    setlist_placing: 'Placement...',
    setlist_place_in: 'Placer dans…',
    setlist_other: 'Autre',
    setlist_choose_set: 'Choisir un set…',
    setlist_filtered: 'Filtrés',
    setlist_all_sets: 'Tous',
    setlist_see_set: 'Voir le set',
    setlist_done: '✓ Fait',
    setlist_season: 'Saison',
    setlist_completed: 'complété',
    setlist_loading: 'Chargement...',
    setlist_no_collection: 'Aucune collection pour cette saison.',
    setlist_cards: 'cartes',
    setlist_owned: 'possédées',

    // Events
    events_sub: 'Card shows, conventions et rencontres de collectionneurs',
    events_propose_btn: '+ Proposer un événement',
    events_loading: 'Chargement...',
    events_none: 'Aucun événement pour le moment.',
    events_propose_first: 'Proposer le premier',
    events_upcoming: 'À venir',
    events_past: 'Passés',
    events_propose_title: 'Proposer un événement',
    events_submitted: "Demande envoyée ! Les admins vont l'examiner.",
    events_event_name: "Nom de l'événement *",
    events_description: 'Description (optionnel)',
    events_city: 'Ville *',
    events_country: 'Pays',
    events_location: 'Lieu (ex: Parc des Expositions)',
    events_website: 'Site web (optionnel)',
    events_uploading: 'Upload...',
    events_add_image: '🖼️ Ajouter une image (optionnel)',
    events_submitting: 'Envoi...',
    events_send: 'Envoyer la demande',
    events_official_site: '🔗 Site officiel',
    events_going: "✅ J'y vais",
    events_going_q: "📌 J'y vais ?",
    events_attendee_one: 'participant',
    events_attendee_other: 'participants',

    // Comments
    comments_placeholder: 'Laisser un commentaire...',
    comments_reply_placeholder: 'Votre réponse...',
    comments_send: 'Commenter',
    comments_reply: 'Répondre',
    comments_sending: 'Envoi...',
    comments_empty: 'Aucun commentaire',
    comments_empty_gallery: 'Soyez le premier à commenter cette galerie',
    comments_login_text: 'pour commenter ou liker',
    comments_close: 'Fermer',
    comments_instant: 'À l\'instant',
    comments_ago: 'Il y a',
    comments_min: 'min',
    comments_day: 'j',

    // Wishlist
    wishlist_title: 'Ma Wishlist',
    wishlist_sub: 'Cartes que vous recherchez',
    wishlist_add: '+ Ajouter une carte',
    wishlist_cancel_add: '✕ Annuler',
    wishlist_new_wanted: 'Nouvelle carte recherchée',
    wishlist_saving: 'Enregistrement...',
    wishlist_submit: 'Ajouter à ma wishlist',
    wishlist_empty_title: 'Aucune carte dans votre wishlist',
    wishlist_empty_sub: 'Ajoutez les cartes que vous recherchez',
    wishlist_owned_by: 'Possédée par :',
    wishlist_none: 'Aucune carte recherchée',
    wishlist_num_label: 'Numérotation',
    wishlist_variation_label: 'Variation',
    wishlist_notes_label: 'Notes',

    // Misc
    collector_label: 'Collectionneur',
    video_format_default: 'Défaut',
    video_format_square: 'Carré',

    // Galerie — chaînes étendues
    gallery_add: 'Ajouter',
    gallery_jewels: 'Les pièces maîtresses',
    gallery_add_card: 'Ajouter une carte',
    gallery_choose_card: 'Choisir une carte',
    gallery_search_collection: 'Rechercher dans ma collection…',
    gallery_type_hint: "Tapez le nom d'un joueur, set ou variation…",
    gallery_no_results: 'Aucun résultat',
    gallery_tab_library: '📔 Classeurs',
    gallery_tab_objectifs: '🎯 Objectifs',
    gallery_tab_comments: '💬 Commentaires',
    gallery_tab_liked: '❤️ Aimées',
    gallery_filter_memo: 'Mémo',
    gallery_filter_sale: 'Vente',
    gallery_filter_private: 'Privé',
    gallery_sort_by: 'Trier par',
    gallery_sort_default: '— Ordre par défaut —',
    gallery_sort_player_group: 'Joueur',
    gallery_sort_player_az: 'Joueur A → Z',
    gallery_sort_player_za: 'Joueur Z → A',
    gallery_sort_year_group: 'Année',
    gallery_sort_year_asc: 'Année croissante',
    gallery_sort_year_desc: 'Année décroissante',
    gallery_sort_team_group: 'Équipe',
    gallery_sort_team_az: 'Équipe A → Z',
    gallery_sort_brand_group: 'Collection',
    gallery_sort_brand_az: 'Collection A → Z',
    gallery_sort_num_group: 'Numérotation',
    gallery_sort_num_asc: 'Numérotation basse → haute',
    gallery_sort_cardnum_group: '# Carte',
    gallery_sort_cardnum_asc: '# Carte croissant',
    gallery_sort_cardnum_desc: '# Carte décroissant',
    gallery_sort_date_group: "Date d'ajout",
    gallery_sort_newest: 'Plus récent en 1er',
    gallery_sort_oldest: 'Plus ancien en 1er',
    gallery_sort_value_desc: 'Valeur ↓ (plus cher en 1er)',
    gallery_sort_value_asc: 'Valeur ↑ (moins cher en 1er)',
    gallery_then_by: 'Puis par',
    gallery_sort_none: '— Aucun tri secondaire —',
    gallery_team_first: '⭐ Équipe en tête',
    gallery_no_team: '— Aucune —',
    gallery_fix_order: '💾 Fixer cet ordre (activer le drag)',
    gallery_my_collection: 'Ma collection',
    gallery_drag_reorder: '· glisser pour réordonner',
    gallery_for_sale_title: 'Disponible à la vente / trade',
    gallery_for_sale_label: 'Vente/Trade',
    gallery_edit_card: 'Modifier la carte',
    gallery_delete_card: 'Supprimer la carte',
    gallery_no_match_title: 'Aucun résultat',
    gallery_no_match_sub: 'Aucune carte ne correspond à ces filtres.',
    gallery_clear_filters: 'Effacer les filtres',
    gallery_get_started: 'Commencer →',
    gallery_close: 'Fermer',
  },
  en: {
    // Navbar
    nav_communaute: 'Community',
    nav_outils: 'Tools',
    nav_evenements: 'Events',
    nav_scanner: 'Price scanner',
    nav_setlist: 'Setlist',
    nav_admin_stats: 'Admin stats',
    nav_my_account: 'My account',
    nav_annuaire: 'Directory',
    nav_teams: 'Teams',
    nav_trades: 'Trades',
    nav_recherche: '🔍 Search',
    nav_tuto: 'Tutorial',
    nav_galerie: 'My gallery',
    nav_messages: 'Messages',
    nav_profil: 'Profile',
    nav_connexion: 'Login',
    nav_inscription: 'Sign up',
    nav_deconnexion: 'Logout',
    nav_mode_clair: '☀️ Light mode',
    nav_mode_sombre: '🌙 Dark mode',

    // Home
    home_hero: 'Collect. Identify. Trade.',
    home_sub: 'Interactive 3D gallery, AI scan, live eBay prices and trading system — the complete platform for card enthusiasts.',
    home_cta1: 'Create my gallery',
    home_cta2: 'View directory',
    home_collectors: 'Collectors',
    home_cards: 'Cards listed',
    home_binders: 'Shared binders',
    home_trade: 'Cards for trade / sale',
    home_pepites: '✨ Latest gems',

    // Gallery
    gallery_search: 'Player, variation...',
    gallery_team: 'Team',
    gallery_all: 'All',
    gallery_collection: 'Collection',
    gallery_year: 'Year',
    gallery_privacy: 'Manage cards',
    gallery_done: '✓ Done',
    gallery_message: '💬 Send a message',
    gallery_share: '🔗 Share',
    gallery_private: '🔒 PRIVATE',
    gallery_make_private: '🔒 Make private',
    gallery_make_public: '🔓 Make public',
    gallery_total: 'card(s) total',

    // Trades
    trades_title: 'Trades',
    trades_post: '+ Post an ad',
    trades_search: 'Search a player, card...',
    trades_all: 'All',
    trades_sport_label: 'Sport:',
    trades_offers: '📤 Offers',
    trades_searches: '📥 Searches',
    trades_sport: 'Sport:',
    trades_tags: 'Tags:',
    trades_by: 'Posted by',
    trades_mark_done: '✓ Mark as completed',
    trades_edit: '✏️ Edit ad',
    trades_delete: '🗑️ Delete ad',
    trades_published: 'Published on',

    // Directory
    directory_title: 'Collectors directory',
    directory_collector: 'Collector',
    directory_total: 'Total',

    // Teams
    teams_title: 'Teams directory',
    teams_create: 'Create my Team',
    teams_search: 'Search a team...',
    teams_members: 'Members',
    teams_total_cards: 'Total cards',
    teams_action: 'Action',
    teams_join: 'Join',
    teams_pending: '⏳ Pending',
    teams_my_team: 'My Team ✓',
    teams_chat: '💬 Chat',
    teams_candidatures: '📋 Applications',
    teams_no_message: 'No messages yet — be the first to write!',
    teams_send: 'Send',
    teams_accept: '✓ Accept',
    teams_refuse: '✗ Decline',
    teams_promote: '↑ Promote',
    teams_demote: '↓ Demote',
    teams_kick: '🚫 Kick',
    teams_leave: 'Leave team',
    teams_modify: '✏️ Edit',
    teams_no_candidatures: 'No pending applications',

    // Profile
    profile_title: 'My profile',
    profile_save: 'Save',
    profile_saved: '✓ Saved!',
    profile_pseudo: 'Username',
    profile_csv: 'Google Sheets CSV link',
    profile_logo: 'Your logo URL',
    profile_border: 'Border color',
    profile_danger: '⚠️ Danger zone',
    profile_delete: 'Delete my account',
    profile_delete_confirm: 'Type DELETE to confirm:',
    profile_delete_btn: 'Delete permanently',
    profile_cancel: 'Cancel',
    profile_photo: 'Profile picture',
    profile_change_photo: '📷 Change my photo',

    // Messages
    messages_title: 'Messages',
    messages_none: 'No conversations',
    messages_select: 'Select a conversation',
    messages_placeholder: 'Your message...',
    messages_send: 'Send',

    // Notifications
    notif_title: '🔔 Notifications',
    notif_none: 'No notifications yet',

    // Auth
    login_title: 'Login',
    login_email: 'Email',
    login_password: 'Password',
    login_btn: 'Sign in',
    login_no_account: 'No account yet?',
    login_forgot: 'Forgot password?',
    register_title: 'Create an account',
    register_sub: 'Join the collectors community',
    register_pseudo: 'Username',
    register_btn: 'Create my account',
    register_have_account: 'Already have an account?',
    register_connect: 'Sign in',

    // 404
    not_found_title: 'This card does not exist',
    not_found_sub: 'The page you are looking for does not exist or has been moved.',
    not_found_home: 'Back to home',
    not_found_directory: 'View directory',

    // Extras
    gallery_cards: 'Cards',
    gallery_search_label: 'Search',
    gallery_team_label: 'Team',
    gallery_collection_label: 'Collection',
    gallery_year_label: 'Year',
    by_label: 'by',
    all_teams: 'All teams',
    directory_back_all_teams: '← All teams',
    directory_all_nba: '🏀 All NBA teams',
    directory_search_placeholder: 'Search collector…',
    teams_role: 'Role',
    teams_cards: 'Cards',
    teams_collector: 'Collector',
    teams_total_cards_label: 'Total cards',
    teams_see_my_team: 'View my team →',
    profile_csv_label: 'Google Sheets CSV link',
    profile_logo_label: 'Your logo URL (gallery)',
    profile_delete_warning: 'Account deletion is irreversible. All your data will be lost.',
    pwa_install: 'Install Memorabilius',
    pwa_sub: 'Quick access from your home screen',
    pwa_later: 'Later',
    pwa_install_btn: 'Install',
    search_title: '🔍 Global search',
    search_sub: 'Search for a card across all community collections',
    search_placeholder: 'Player name, team, variant...',
    search_min_chars: 'Type at least 2 characters',
    search_results: 'card(s) found for',
    search_none: 'No cards found for',
    search_none_sub: 'Try a different name or check the spelling',
    tuto_video: '🎬 Video Tutorial',
    tuto_title: 'How to create your gallery',
    tuto_sub: 'Follow these 4 simple steps to link your Google Sheets collection to Memorabilius.',

    // Profile - extras
    profile_fav_teams: 'Favorite teams (max 5)',
    profile_wrap_before: 'Receive the ',
    profile_wrap_name: 'Monthly Wrap',
    profile_wrap_after: ' by email (a summary of your collection every 1st of the month)',
    profile_password: 'Password',
    profile_password_change: 'Change password',
    profile_password_new: 'New password',
    profile_password_confirm: 'Confirm password',
    profile_password_min: 'Min. 8 characters',
    profile_password_repeat: 'Repeat password',
    profile_password_saving: 'Saving...',
    profile_password_save: 'Save',
    profile_password_mismatch: 'Passwords do not match.',
    profile_password_tooshort: 'Password must be at least 8 characters.',
    profile_password_success: 'Password changed successfully!',
    profile_status_label: 'Status:',
    profile_status_synced: 'Collection synced 🟢',
    profile_status_none: 'No collection linked 🔴',
    profile_status_hint: 'Add your CSV link below to activate your gallery.',
    profile_view_gallery: 'View my gallery →',
    profile_uploading: 'Uploading...',
    profile_bio_label: 'Bio',
    profile_bio_placeholder: 'Describe your collection in a few words...',
    profile_bio_chars: 'characters',
    profile_csv_hint: 'File > Share > Publish to web > CSV',

    // Setlist
    setlist_collections_available: 'collections available',
    setlist_sync_btn: '🔄 Sync my gallery',
    setlist_syncing: 'Syncing...',
    setlist_new_match_one: 'new card checked',
    setlist_new_match_other: 'new cards checked',
    setlist_cards_synced: 'cards synced',
    setlist_in: 'in',
    setlist_see_unplaced: 'View unplaced cards',
    setlist_unplaced_title: 'Cards not placed in a setlist',
    setlist_sync_first: 'Run a sync to see which cards in your gallery are not in a setlist.',
    setlist_all_placed: 'All your cards are placed in a setlist 🎉',
    setlist_card_no_match: 'card without a match. Choose a setlist to place it.',
    setlist_cards_no_match: 'cards without a match. Choose a setlist to place them.',
    setlist_add_manual: '+ Add a card manually',
    setlist_player: 'Player *',
    setlist_year_ex: 'Year (ex: 2024-25)',
    setlist_brand: 'Brand',
    setlist_add: 'Add',
    setlist_placing: 'Placing...',
    setlist_place_in: 'Place in…',
    setlist_other: 'Other',
    setlist_choose_set: 'Choose a set…',
    setlist_filtered: 'Filtered',
    setlist_all_sets: 'All',
    setlist_see_set: 'View set',
    setlist_done: '✓ Done',
    setlist_season: 'Season',
    setlist_completed: 'complete',
    setlist_loading: 'Loading...',
    setlist_no_collection: 'No collection for this season.',
    setlist_cards: 'cards',
    setlist_owned: 'owned',

    // Events
    events_sub: 'Card shows, conventions and collector meetups',
    events_propose_btn: '+ Propose an event',
    events_loading: 'Loading...',
    events_none: 'No events yet.',
    events_propose_first: 'Be the first',
    events_upcoming: 'Upcoming',
    events_past: 'Past',
    events_propose_title: 'Propose an event',
    events_submitted: 'Request sent! Admins will review it.',
    events_event_name: 'Event name *',
    events_description: 'Description (optional)',
    events_city: 'City *',
    events_country: 'Country',
    events_location: 'Venue (e.g., Convention Center)',
    events_website: 'Website (optional)',
    events_uploading: 'Uploading...',
    events_add_image: '🖼️ Add an image (optional)',
    events_submitting: 'Sending...',
    events_send: 'Send request',
    events_official_site: '🔗 Official website',
    events_going: '✅ Going',
    events_going_q: '📌 Going?',
    events_attendee_one: 'attendee',
    events_attendee_other: 'attendees',

    // Comments
    comments_placeholder: 'Leave a comment...',
    comments_reply_placeholder: 'Your reply...',
    comments_send: 'Comment',
    comments_reply: 'Reply',
    comments_sending: 'Sending...',
    comments_empty: 'No comments',
    comments_empty_gallery: 'Be the first to comment on this gallery',
    comments_login_text: 'to comment or like',
    comments_close: 'Close',
    comments_instant: 'Just now',
    comments_ago: '',
    comments_min: 'min ago',
    comments_day: 'd ago',

    // Wishlist
    wishlist_title: 'My Wishlist',
    wishlist_sub: 'Cards you are looking for',
    wishlist_add: '+ Add a card',
    wishlist_cancel_add: '✕ Cancel',
    wishlist_new_wanted: 'New wanted card',
    wishlist_saving: 'Saving...',
    wishlist_submit: 'Add to my wishlist',
    wishlist_empty_title: 'No cards in your wishlist',
    wishlist_empty_sub: 'Add the cards you are looking for',
    wishlist_owned_by: 'Owned by:',
    wishlist_none: 'No wanted cards',
    wishlist_num_label: 'Print run',
    wishlist_variation_label: 'Variation',
    wishlist_notes_label: 'Notes',

    // Misc
    collector_label: 'Collector',
    video_format_default: 'Default',
    video_format_square: 'Square',

    // Gallery — extended strings
    gallery_add: 'Add',
    gallery_jewels: 'The crown jewels',
    gallery_add_card: 'Add a card',
    gallery_choose_card: 'Choose a card',
    gallery_search_collection: 'Search my collection…',
    gallery_type_hint: 'Type a player name, set or variation…',
    gallery_no_results: 'No results',
    gallery_tab_library: '📔 Binders',
    gallery_tab_objectifs: '🎯 Goals',
    gallery_tab_comments: '💬 Comments',
    gallery_tab_liked: '❤️ Liked',
    gallery_filter_memo: 'Memo',
    gallery_filter_sale: 'Sale',
    gallery_filter_private: 'Private',
    gallery_sort_by: 'Sort by',
    gallery_sort_default: '— Default order —',
    gallery_sort_player_group: 'Player',
    gallery_sort_player_az: 'Player A → Z',
    gallery_sort_player_za: 'Player Z → A',
    gallery_sort_year_group: 'Year',
    gallery_sort_year_asc: 'Year asc',
    gallery_sort_year_desc: 'Year desc',
    gallery_sort_team_group: 'Team',
    gallery_sort_team_az: 'Team A → Z',
    gallery_sort_brand_group: 'Brand',
    gallery_sort_brand_az: 'Brand A → Z',
    gallery_sort_num_group: 'Numbering',
    gallery_sort_num_asc: 'Numbering low → high',
    gallery_sort_cardnum_group: 'Card #',
    gallery_sort_cardnum_asc: 'Card # low → high',
    gallery_sort_cardnum_desc: 'Card # high → low',
    gallery_sort_date_group: 'Date added',
    gallery_sort_newest: 'Newest first',
    gallery_sort_oldest: 'Oldest first',
    gallery_sort_value_desc: 'Value ↓ (highest first)',
    gallery_sort_value_asc: 'Value ↑ (lowest first)',
    gallery_then_by: 'Then by',
    gallery_sort_none: '— No secondary sort —',
    gallery_team_first: '⭐ Team first',
    gallery_no_team: '— None —',
    gallery_fix_order: '💾 Fix order (enable drag)',
    gallery_my_collection: 'My collection',
    gallery_drag_reorder: '· drag to reorder',
    gallery_for_sale_title: 'Available for sale / trade',
    gallery_for_sale_label: 'For Sale',
    gallery_edit_card: 'Edit card',
    gallery_delete_card: 'Delete card',
    gallery_no_match_title: 'No results',
    gallery_no_match_sub: 'No cards match these filters.',
    gallery_clear_filters: 'Clear filters',
    gallery_get_started: 'Get started →',
    gallery_close: 'Close',
  },
  de: {
    // Navbar
    nav_communaute: 'Community',
    nav_outils: 'Tools',
    nav_evenements: 'Veranstaltungen',
    nav_scanner: 'Preisscanner',
    nav_setlist: 'Setlist',
    nav_admin_stats: 'Admin-Statistiken',
    nav_my_account: 'Mein Konto',
    nav_annuaire: 'Verzeichnis',
    nav_teams: 'Teams',
    nav_trades: 'Tauschbörse',
    nav_recherche: '🔍 Suche',
    nav_tuto: 'Tutorial',
    nav_galerie: 'Meine Galerie',
    nav_messages: 'Nachrichten',
    nav_profil: 'Profil',
    nav_connexion: 'Anmelden',
    nav_inscription: 'Registrieren',
    nav_deconnexion: 'Abmelden',
    nav_mode_clair: '☀️ Heller Modus',
    nav_mode_sombre: '🌙 Dunkler Modus',

    // Startseite
    home_hero: 'Sammeln. Identifizieren. Tauschen.',
    home_sub: 'Interaktive 3D-Galerie, KI-Scan, Live-eBay-Preise und Tauschsystem — die komplette Plattform für Kartenliebhaber.',
    home_cta1: 'Meine Galerie erstellen',
    home_cta2: 'Verzeichnis ansehen',
    home_collectors: 'Sammler',
    home_cards: 'Erfasste Karten',
    home_binders: 'Geteilte Ordner',
    home_trade: 'Karten zum Tauschen / Verkaufen',
    home_pepites: '✨ Neueste Highlights',

    // Galerie
    gallery_search: 'Spieler, Variante...',
    gallery_team: 'Team',
    gallery_all: 'Alle',
    gallery_collection: 'Kollektion',
    gallery_year: 'Jahr',
    gallery_privacy: 'Karten verwalten',
    gallery_done: '✓ Fertig',
    gallery_message: '💬 Nachricht senden',
    gallery_share: '🔗 Teilen',
    gallery_private: '🔒 PRIVAT',
    gallery_make_private: '🔒 Privat machen',
    gallery_make_public: '🔓 Öffentlich machen',
    gallery_total: 'Karte(n) insgesamt',

    // Tauschbörse
    trades_title: 'Tauschbörse',
    trades_post: '+ Anzeige aufgeben',
    trades_search: 'Spieler, Karte suchen...',
    trades_all: 'Alle',
    trades_sport_label: 'Sport:',
    trades_offers: '📤 Angebote',
    trades_searches: '📥 Gesuche',
    trades_sport: 'Sport:',
    trades_tags: 'Tags:',
    trades_by: 'Angeboten von',
    trades_mark_done: '✓ Als abgeschlossen markieren',
    trades_edit: '✏️ Anzeige bearbeiten',
    trades_delete: '🗑️ Anzeige löschen',
    trades_published: 'Veröffentlicht am',

    // Verzeichnis
    directory_title: 'Sammler-Verzeichnis',
    directory_collector: 'Sammler',
    directory_total: 'Gesamt',

    // Teams
    teams_title: 'Team-Verzeichnis',
    teams_create: 'Mein Team erstellen',
    teams_search: 'Team suchen...',
    teams_members: 'Mitglieder',
    teams_total_cards: 'Karten gesamt',
    teams_action: 'Aktion',
    teams_join: 'Beitreten',
    teams_pending: '⏳ Ausstehend',
    teams_my_team: 'Mein Team ✓',
    teams_chat: '💬 Chat',
    teams_candidatures: '📋 Bewerbungen',
    teams_no_message: 'Noch keine Nachrichten — schreibe die erste!',
    teams_send: 'Senden',
    teams_accept: '✓ Akzeptieren',
    teams_refuse: '✗ Ablehnen',
    teams_promote: '↑ Befördern',
    teams_demote: '↓ Degradieren',
    teams_kick: '🚫 Kicken',
    teams_leave: 'Team verlassen',
    teams_modify: '✏️ Bearbeiten',
    teams_no_candidatures: 'Keine ausstehenden Bewerbungen',

    // Profil
    profile_title: 'Mein Profil',
    profile_save: 'Speichern',
    profile_saved: '✓ Gespeichert!',
    profile_pseudo: 'Benutzername',
    profile_csv: 'Google Sheets CSV-Link',
    profile_logo: 'Logo-URL',
    profile_border: 'Rahmenfarbe',
    profile_danger: '⚠️ Gefahrenzone',
    profile_delete: 'Konto löschen',
    profile_delete_confirm: 'Gib LÖSCHEN ein zur Bestätigung:',
    profile_delete_btn: 'Endgültig löschen',
    profile_cancel: 'Abbrechen',
    profile_photo: 'Profilbild',
    profile_change_photo: '📷 Foto ändern',

    // Nachrichten
    messages_title: 'Nachrichten',
    messages_none: 'Keine Unterhaltungen',
    messages_select: 'Unterhaltung auswählen',
    messages_placeholder: 'Ihre Nachricht...',
    messages_send: 'Senden',

    // Benachrichtigungen
    notif_title: '🔔 Benachrichtigungen',
    notif_none: 'Noch keine Benachrichtigungen',

    // Auth
    login_title: 'Anmelden',
    login_email: 'E-Mail',
    login_password: 'Passwort',
    login_btn: 'Anmelden',
    login_no_account: 'Noch kein Konto?',
    login_forgot: 'Passwort vergessen?',
    register_title: 'Konto erstellen',
    register_sub: 'Der Sammler-Community beitreten',
    register_pseudo: 'Benutzername',
    register_btn: 'Mein Konto erstellen',
    register_have_account: 'Bereits ein Konto?',
    register_connect: 'Anmelden',

    // 404
    not_found_title: 'Diese Karte existiert nicht',
    not_found_sub: 'Die gesuchte Seite existiert nicht oder wurde verschoben.',
    not_found_home: 'Zurück zur Startseite',
    not_found_directory: 'Verzeichnis ansehen',

    // Extras
    gallery_cards: 'Karten',
    gallery_search_label: 'Suche',
    gallery_team_label: 'Team',
    gallery_collection_label: 'Kollektion',
    gallery_year_label: 'Jahr',
    by_label: 'von',
    all_teams: 'Alle Teams',
    directory_back_all_teams: '← Alle Teams',
    directory_all_nba: '🏀 Alle NBA-Teams',
    directory_search_placeholder: 'Sammler suchen…',
    teams_role: 'Rolle',
    teams_cards: 'Karten',
    teams_collector: 'Sammler',
    teams_total_cards_label: 'Karten gesamt',
    teams_see_my_team: 'Mein Team ansehen →',
    profile_csv_label: 'Google Sheets CSV-Link',
    profile_logo_label: 'Logo-URL (Galerie)',
    profile_delete_warning: 'Das Löschen des Kontos ist unwiderruflich. Alle Daten gehen verloren.',
    pwa_install: 'Memorabilius installieren',
    pwa_sub: 'Schnellzugriff vom Startbildschirm',
    pwa_later: 'Später',
    pwa_install_btn: 'Installieren',
    search_title: '🔍 Globale Suche',
    search_sub: 'Karten in allen Community-Sammlungen suchen',
    search_placeholder: 'Spielername, Team, Variante...',
    search_min_chars: 'Mindestens 2 Zeichen eingeben',
    search_results: 'Karte(n) gefunden für',
    search_none: 'Keine Karten gefunden für',
    search_none_sub: 'Anderen Namen versuchen oder Schreibweise prüfen',
    tuto_video: '🎬 Video-Tutorial',
    tuto_title: 'Wie du deine Galerie erstellst',
    tuto_sub: 'Folge diesen 4 einfachen Schritten, um deine Google-Sheets-Sammlung mit Memorabilius zu verknüpfen.',

    // Profil - extras
    profile_fav_teams: 'Lieblingsteams (max. 5)',
    profile_wrap_before: 'Den ',
    profile_wrap_name: 'Monatlichen Wrap',
    profile_wrap_after: ' per E-Mail erhalten (Zusammenfassung deiner Sammlung jeden 1. des Monats)',
    profile_password: 'Passwort',
    profile_password_change: 'Passwort ändern',
    profile_password_new: 'Neues Passwort',
    profile_password_confirm: 'Passwort bestätigen',
    profile_password_min: 'Min. 8 Zeichen',
    profile_password_repeat: 'Passwort wiederholen',
    profile_password_saving: 'Wird gespeichert...',
    profile_password_save: 'Speichern',
    profile_password_mismatch: 'Passwörter stimmen nicht überein.',
    profile_password_tooshort: 'Passwort muss mindestens 8 Zeichen haben.',
    profile_password_success: 'Passwort erfolgreich geändert!',
    profile_status_label: 'Status:',
    profile_status_synced: 'Sammlung synchronisiert 🟢',
    profile_status_none: 'Keine Sammlung verknüpft 🔴',
    profile_status_hint: 'CSV-Link unten hinzufügen, um die Galerie zu aktivieren.',
    profile_view_gallery: 'Meine Galerie ansehen →',
    profile_uploading: 'Wird hochgeladen...',
    profile_bio_label: 'Bio',
    profile_bio_placeholder: 'Deine Sammlung in wenigen Worten beschreiben...',
    profile_bio_chars: 'Zeichen',
    profile_csv_hint: 'Datei > Teilen > Im Web veröffentlichen > CSV',

    // Setlist
    setlist_collections_available: 'Kollektionen verfügbar',
    setlist_sync_btn: '🔄 Galerie synchronisieren',
    setlist_syncing: 'Synchronisierung...',
    setlist_new_match_one: 'neue Karte abgehakt',
    setlist_new_match_other: 'neue Karten abgehakt',
    setlist_cards_synced: 'Karten synchronisiert',
    setlist_in: 'in',
    setlist_see_unplaced: 'Nicht platzierte Karten ansehen',
    setlist_unplaced_title: 'Karten ohne Setlist-Platz',
    setlist_sync_first: 'Starte eine Synchronisierung, um zu sehen, welche Karten in deiner Galerie keinem Setlist zugeordnet sind.',
    setlist_all_placed: 'Alle deine Karten sind in einem Setlist platziert 🎉',
    setlist_card_no_match: 'Karte ohne Übereinstimmung. Setlist auswählen.',
    setlist_cards_no_match: 'Karten ohne Übereinstimmung. Setlist auswählen.',
    setlist_add_manual: '+ Karte manuell hinzufügen',
    setlist_player: 'Spieler *',
    setlist_year_ex: 'Jahr (z.B.: 2024-25)',
    setlist_brand: 'Marke',
    setlist_add: 'Hinzufügen',
    setlist_placing: 'Wird platziert...',
    setlist_place_in: 'Einordnen in…',
    setlist_other: 'Andere',
    setlist_choose_set: 'Set auswählen…',
    setlist_filtered: 'Gefiltert',
    setlist_all_sets: 'Alle',
    setlist_see_set: 'Set ansehen',
    setlist_done: '✓ Fertig',
    setlist_season: 'Saison',
    setlist_completed: 'abgeschlossen',
    setlist_loading: 'Wird geladen...',
    setlist_no_collection: 'Keine Kollektion für diese Saison.',
    setlist_cards: 'Karten',
    setlist_owned: 'besessen',

    // Veranstaltungen
    events_sub: 'Card Shows, Conventions und Sammler-Treffen',
    events_propose_btn: '+ Veranstaltung vorschlagen',
    events_loading: 'Wird geladen...',
    events_none: 'Noch keine Veranstaltungen.',
    events_propose_first: 'Erste vorschlagen',
    events_upcoming: 'Bevorstehend',
    events_past: 'Vergangen',
    events_propose_title: 'Veranstaltung vorschlagen',
    events_submitted: 'Anfrage gesendet! Die Admins werden sie prüfen.',
    events_event_name: 'Veranstaltungsname *',
    events_description: 'Beschreibung (optional)',
    events_city: 'Stadt *',
    events_country: 'Land',
    events_location: 'Ort (z.B.: Messehalle)',
    events_website: 'Website (optional)',
    events_uploading: 'Wird hochgeladen...',
    events_add_image: '🖼️ Bild hinzufügen (optional)',
    events_submitting: 'Wird gesendet...',
    events_send: 'Anfrage senden',
    events_official_site: '🔗 Offizielle Website',
    events_going: '✅ Ich gehe',
    events_going_q: '📌 Ich gehe?',
    events_attendee_one: 'Teilnehmer',
    events_attendee_other: 'Teilnehmer',

    // Kommentare
    comments_placeholder: 'Kommentar hinterlassen...',
    comments_reply_placeholder: 'Ihre Antwort...',
    comments_send: 'Kommentieren',
    comments_reply: 'Antworten',
    comments_sending: 'Wird gesendet...',
    comments_empty: 'Keine Kommentare',
    comments_empty_gallery: 'Sei der Erste, der diese Galerie kommentiert',
    comments_login_text: 'um zu kommentieren oder zu liken',
    comments_close: 'Schließen',
    comments_instant: 'Gerade eben',
    comments_ago: 'Vor',
    comments_min: ' Min.',
    comments_day: ' T.',

    // Wunschliste
    wishlist_title: 'Meine Wunschliste',
    wishlist_sub: 'Karten, die Sie suchen',
    wishlist_add: '+ Karte hinzufügen',
    wishlist_cancel_add: '✕ Abbrechen',
    wishlist_new_wanted: 'Neue gesuchte Karte',
    wishlist_saving: 'Wird gespeichert...',
    wishlist_submit: 'Zur Wunschliste hinzufügen',
    wishlist_empty_title: 'Keine Karten auf der Wunschliste',
    wishlist_empty_sub: 'Gesuchte Karten hinzufügen',
    wishlist_owned_by: 'Im Besitz von:',
    wishlist_none: 'Keine gesuchten Karten',
    wishlist_num_label: 'Nummerierung',
    wishlist_variation_label: 'Variante',
    wishlist_notes_label: 'Notizen',

    // Misc
    collector_label: 'Sammler',
    video_format_default: 'Standard',
    video_format_square: 'Quadrat',

    // Galerie — erweiterte Strings
    gallery_add: 'Hinzufügen',
    gallery_jewels: 'Die Kronjuwelen',
    gallery_add_card: 'Karte hinzufügen',
    gallery_choose_card: 'Karte auswählen',
    gallery_search_collection: 'In meiner Sammlung suchen…',
    gallery_type_hint: 'Spieler, Set oder Variante eingeben…',
    gallery_no_results: 'Keine Ergebnisse',
    gallery_tab_library: '📔 Ordner',
    gallery_tab_objectifs: '🎯 Ziele',
    gallery_tab_comments: '💬 Kommentare',
    gallery_tab_liked: '❤️ Gefällt mir',
    gallery_filter_memo: 'Memo',
    gallery_filter_sale: 'Verkauf',
    gallery_filter_private: 'Privat',
    gallery_sort_by: 'Sortieren nach',
    gallery_sort_default: '— Standardreihenfolge —',
    gallery_sort_player_group: 'Spieler',
    gallery_sort_player_az: 'Spieler A → Z',
    gallery_sort_player_za: 'Spieler Z → A',
    gallery_sort_year_group: 'Jahr',
    gallery_sort_year_asc: 'Jahr aufsteigend',
    gallery_sort_year_desc: 'Jahr absteigend',
    gallery_sort_team_group: 'Team',
    gallery_sort_team_az: 'Team A → Z',
    gallery_sort_brand_group: 'Marke',
    gallery_sort_brand_az: 'Marke A → Z',
    gallery_sort_num_group: 'Nummerierung',
    gallery_sort_num_asc: 'Nummerierung niedrig → hoch',
    gallery_sort_cardnum_group: '# Karte',
    gallery_sort_cardnum_asc: 'Karte # niedrig → hoch',
    gallery_sort_cardnum_desc: 'Karte # hoch → niedrig',
    gallery_sort_date_group: 'Hinzugefügt am',
    gallery_sort_newest: 'Neueste zuerst',
    gallery_sort_oldest: 'Älteste zuerst',
    gallery_sort_value_desc: 'Wert ↓ (teuerste zuerst)',
    gallery_sort_value_asc: 'Wert ↑ (günstigste zuerst)',
    gallery_then_by: 'Dann nach',
    gallery_sort_none: '— Keine zweite Sortierung —',
    gallery_team_first: '⭐ Team zuerst',
    gallery_no_team: '— Keine —',
    gallery_fix_order: '💾 Reihenfolge festlegen (Drag aktivieren)',
    gallery_my_collection: 'Meine Sammlung',
    gallery_drag_reorder: '· ziehen zum Neuanordnen',
    gallery_for_sale_title: 'Zum Verkauf / Tausch verfügbar',
    gallery_for_sale_label: 'Verkauf/Tausch',
    gallery_edit_card: 'Karte bearbeiten',
    gallery_delete_card: 'Karte löschen',
    gallery_no_match_title: 'Keine Ergebnisse',
    gallery_no_match_sub: 'Keine Karten entsprechen diesen Filtern.',
    gallery_clear_filters: 'Filter löschen',
    gallery_get_started: 'Loslegen →',
    gallery_close: 'Schließen',
  },
}

type TranslationKey = keyof typeof translations.fr

const LangContext = createContext<{
  lang: Lang
  setLang: (l: Lang) => void
  t: (key: TranslationKey) => string
}>({ lang: 'fr', setLang: () => {}, t: (k) => k })

export function LangProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>('fr')

  useEffect(() => {
    const saved = localStorage.getItem('lang') as Lang
    if (saved === 'fr' || saved === 'en' || saved === 'de') { setLangState(saved); return }
    const geo = document.cookie.split(';').find(c => c.trim().startsWith('geo-lang='))?.split('=')?.[1]?.trim() as Lang | undefined
    if (geo === 'fr' || geo === 'en' || geo === 'de') { setLangState(geo); return }
    const browser: Lang = navigator.language.startsWith('en') ? 'en' : navigator.language.startsWith('de') ? 'de' : 'fr'
    setLangState(browser)
  }, [])

  const setLang = (l: Lang) => {
    setLangState(l)
    localStorage.setItem('lang', l)
  }

  const t = (key: TranslationKey): string => translations[lang][key] || translations.fr[key] || key

  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  )
}

export const useLang = () => useContext(LangContext)
