// Couleurs principale + secondaire par equipe (NBA, NFL, NHL, MLB) : meme table que la page joueur, partagee pour le visualiseur.
export const TEAM_COLORS: Record<string, { primary: string; secondary: string; abbr: string }> = {
  'Atlanta Hawks': { primary: '#E03A3E', secondary: '#C1D32F', abbr: 'ATL' },
  'Boston Celtics': { primary: '#007A33', secondary: '#FFFFFF', abbr: 'BOS' },
  'Brooklyn Nets': { primary: '#000000', secondary: '#FFFFFF', abbr: 'BKN' },
  'Charlotte Hornets': { primary: '#1D1160', secondary: '#00788C', abbr: 'CHA' },
  'Chicago Bulls': { primary: '#CE1141', secondary: '#FFFFFF', abbr: 'CHI' },
  'Cleveland Cavaliers': { primary: '#860038', secondary: '#FDBB30', abbr: 'CLE' },
  'Dallas Mavericks': { primary: '#00538C', secondary: '#FFFFFF', abbr: 'DAL' },
  'Denver Nuggets': { primary: '#0E2240', secondary: '#FEC524', abbr: 'DEN' },
  'Detroit Pistons': { primary: '#C8102E', secondary: '#1D428A', abbr: 'DET' },
  'Golden State Warriors': { primary: '#1D428A', secondary: '#FFC72C', abbr: 'GSW' },
  'Houston Rockets': { primary: '#CE1141', secondary: '#FFFFFF', abbr: 'HOU' },
  'Indiana Pacers': { primary: '#002D62', secondary: '#FDBB30', abbr: 'IND' },
  'Los Angeles Clippers': { primary: '#C8102E', secondary: '#1D428A', abbr: 'LAC' },
  'Los Angeles Lakers': { primary: '#552583', secondary: '#FDB927', abbr: 'LAL' },
  'Memphis Grizzlies': { primary: '#5D76A9', secondary: '#12173F', abbr: 'MEM' },
  'Miami Heat': { primary: '#98002E', secondary: '#F9A01B', abbr: 'MIA' },
  'Milwaukee Bucks': { primary: '#00471B', secondary: '#EEE1C6', abbr: 'MIL' },
  'Minnesota Timberwolves': { primary: '#0C2340', secondary: '#236192', abbr: 'MIN' },
  'New Orleans Pelicans': { primary: '#0C2340', secondary: '#85714D', abbr: 'NOP' },
  'New York Knicks': { primary: '#006BB6', secondary: '#F58426', abbr: 'NYK' },
  'Oklahoma City Thunder': { primary: '#007AC1', secondary: '#EF3B24', abbr: 'OKC' },
  'Orlando Magic': { primary: '#0077C0', secondary: '#C4CED4', abbr: 'ORL' },
  'Philadelphia 76ers': { primary: '#006BB6', secondary: '#ED174C', abbr: 'PHI' },
  'Phoenix Suns': { primary: '#1D1160', secondary: '#E56020', abbr: 'PHX' },
  'Portland Trail Blazers': { primary: '#E03A3E', secondary: '#000000', abbr: 'POR' },
  'Sacramento Kings': { primary: '#5A2D81', secondary: '#63727A', abbr: 'SAC' },
  'San Antonio Spurs': { primary: '#C4CED4', secondary: '#000000', abbr: 'SAS' },
  'Toronto Raptors': { primary: '#CE1141', secondary: '#000000', abbr: 'TOR' },
  'Utah Jazz': { primary: '#002B5C', secondary: '#00471B', abbr: 'UTA' },
  'Washington Wizards': { primary: '#002B5C', secondary: '#E31837', abbr: 'WAS' },
  // NBA historiques
  'New Jersey Nets': { primary: '#000000', secondary: '#FFFFFF', abbr: 'NJN' },
  'Seattle SuperSonics': { primary: '#00653A', secondary: '#FFC200', abbr: 'SEA' },
  'Vancouver Grizzlies': { primary: '#29727C', secondary: '#E43C40', abbr: 'VAN' },
  'New Orleans Hornets': { primary: '#002B5C', secondary: '#00788C', abbr: 'NOH' },
  'Charlotte Bobcats': { primary: '#F26522', secondary: '#2D5DAA', abbr: 'BOB' },
  'New Orleans/Oklahoma City Hornets': { primary: '#002B5C', secondary: '#00788C', abbr: 'NOK' },
  // ── NFL ──────────────────────────────────────────────────────────────────────
  'Arizona Cardinals': { primary: '#97233F', secondary: '#FFB612', abbr: 'ARI' },
  'Atlanta Falcons': { primary: '#A71930', secondary: '#000000', abbr: 'ATL' },
  'Baltimore Ravens': { primary: '#241773', secondary: '#9E7C0C', abbr: 'BAL' },
  'Buffalo Bills': { primary: '#00338D', secondary: '#C60C30', abbr: 'BUF' },
  'Carolina Panthers': { primary: '#0085CA', secondary: '#101820', abbr: 'CAR' },
  'Chicago Bears': { primary: '#0B162A', secondary: '#C83803', abbr: 'CHI' },
  'Cincinnati Bengals': { primary: '#FB4F14', secondary: '#000000', abbr: 'CIN' },
  'Cleveland Browns': { primary: '#311D00', secondary: '#FF3C00', abbr: 'CLE' },
  'Dallas Cowboys': { primary: '#003594', secondary: '#869397', abbr: 'DAL' },
  'Denver Broncos': { primary: '#FB4F14', secondary: '#002244', abbr: 'DEN' },
  'Detroit Lions': { primary: '#0076B6', secondary: '#B0B7BC', abbr: 'DET' },
  'Green Bay Packers': { primary: '#203731', secondary: '#FFB612', abbr: 'GB' },
  'Houston Texans': { primary: '#03202F', secondary: '#A71930', abbr: 'HOU' },
  'Indianapolis Colts': { primary: '#002C5F', secondary: '#A2AAAD', abbr: 'IND' },
  'Jacksonville Jaguars': { primary: '#101820', secondary: '#D7A22A', abbr: 'JAX' },
  'Kansas City Chiefs': { primary: '#E31837', secondary: '#FFB81C', abbr: 'KC' },
  'Las Vegas Raiders': { primary: '#000000', secondary: '#A5ACAF', abbr: 'LV' },
  'Los Angeles Chargers': { primary: '#0080C6', secondary: '#FFC20E', abbr: 'LAC' },
  'Los Angeles Rams': { primary: '#003594', secondary: '#FFA300', abbr: 'LAR' },
  'Miami Dolphins': { primary: '#008E97', secondary: '#FC4C02', abbr: 'MIA' },
  'Minnesota Vikings': { primary: '#4F2683', secondary: '#FFC62F', abbr: 'MIN' },
  'New England Patriots': { primary: '#002244', secondary: '#C60C30', abbr: 'NE' },
  'New Orleans Saints': { primary: '#101820', secondary: '#D3BC8D', abbr: 'NO' },
  'New York Giants': { primary: '#0B2265', secondary: '#A71930', abbr: 'NYG' },
  'New York Jets': { primary: '#125740', secondary: '#FFFFFF', abbr: 'NYJ' },
  'Philadelphia Eagles': { primary: '#004C54', secondary: '#A5ACAF', abbr: 'PHI' },
  'Pittsburgh Steelers': { primary: '#101820', secondary: '#FFB612', abbr: 'PIT' },
  'San Francisco 49ers': { primary: '#AA0000', secondary: '#B3995D', abbr: 'SF' },
  'Seattle Seahawks': { primary: '#002244', secondary: '#69BE28', abbr: 'SEA' },
  'Tampa Bay Buccaneers': { primary: '#D50A0A', secondary: '#FF7900', abbr: 'TB' },
  'Tennessee Titans': { primary: '#0C2340', secondary: '#4B92DB', abbr: 'TEN' },
  'Washington Commanders': { primary: '#5A1414', secondary: '#FFB612', abbr: 'WAS' },
  'Oakland Raiders': { primary: '#000000', secondary: '#A5ACAF', abbr: 'OAK' },
  'San Diego Chargers': { primary: '#0073CF', secondary: '#FFC20E', abbr: 'SD' },
  'St. Louis Rams': { primary: '#003594', secondary: '#FFA300', abbr: 'STL' },
  'Washington Redskins': { primary: '#773141', secondary: '#FFB612', abbr: 'WAS' },
  'Washington Football Team': { primary: '#5A1414', secondary: '#FFB612', abbr: 'WFT' },
  // ── NHL ──────────────────────────────────────────────────────────────────────
  'Anaheim Ducks': { primary: '#F47A38', secondary: '#B9975B', abbr: 'ANA' },
  'Boston Bruins': { primary: '#FFB81C', secondary: '#000000', abbr: 'BOS' },
  'Buffalo Sabres': { primary: '#002654', secondary: '#FCB514', abbr: 'BUF' },
  'Calgary Flames': { primary: '#C8102E', secondary: '#F1BE48', abbr: 'CGY' },
  'Carolina Hurricanes': { primary: '#CC0000', secondary: '#000000', abbr: 'CAR' },
  'Chicago Blackhawks': { primary: '#CF0A2C', secondary: '#FF6720', abbr: 'CHI' },
  'Colorado Avalanche': { primary: '#6F263D', secondary: '#236192', abbr: 'COL' },
  'Columbus Blue Jackets': { primary: '#002654', secondary: '#CE1126', abbr: 'CBJ' },
  'Dallas Stars': { primary: '#006847', secondary: '#8F8F8C', abbr: 'DAL' },
  'Detroit Red Wings': { primary: '#CE1126', secondary: '#FFFFFF', abbr: 'DET' },
  'Edmonton Oilers': { primary: '#FF4C00', secondary: '#041E42', abbr: 'EDM' },
  'Florida Panthers': { primary: '#041E42', secondary: '#C8102E', abbr: 'FLA' },
  'Los Angeles Kings': { primary: '#111111', secondary: '#A2AAAD', abbr: 'LAK' },
  'Minnesota Wild': { primary: '#154734', secondary: '#A6192E', abbr: 'MIN' },
  'Montréal Canadiens': { primary: '#AF1E2D', secondary: '#192168', abbr: 'MTL' },
  'Nashville Predators': { primary: '#041E42', secondary: '#FFB81C', abbr: 'NSH' },
  'New Jersey Devils': { primary: '#CE1126', secondary: '#000000', abbr: 'NJD' },
  'New York Islanders': { primary: '#00539B', secondary: '#F47D30', abbr: 'NYI' },
  'New York Rangers': { primary: '#0038A8', secondary: '#CE1126', abbr: 'NYR' },
  'Ottawa Senators': { primary: '#E31837', secondary: '#C69214', abbr: 'OTT' },
  'Philadelphia Flyers': { primary: '#F74902', secondary: '#000000', abbr: 'PHI' },
  'Pittsburgh Penguins': { primary: '#000000', secondary: '#FCB514', abbr: 'PIT' },
  'San Jose Sharks': { primary: '#006D75', secondary: '#EA7200', abbr: 'SJS' },
  'Seattle Kraken': { primary: '#001628', secondary: '#99D9D9', abbr: 'SEA' },
  'St. Louis Blues': { primary: '#002F87', secondary: '#FCB514', abbr: 'STL' },
  'Tampa Bay Lightning': { primary: '#002868', secondary: '#FFFFFF', abbr: 'TBL' },
  'Toronto Maple Leafs': { primary: '#00205B', secondary: '#FFFFFF', abbr: 'TOR' },
  'Utah Hockey Club': { primary: '#6CACE4', secondary: '#010101', abbr: 'UTA' },
  'Vancouver Canucks': { primary: '#00205B', secondary: '#00843D', abbr: 'VAN' },
  'Vegas Golden Knights': { primary: '#B4975A', secondary: '#333F42', abbr: 'VGK' },
  'Washington Capitals': { primary: '#041E42', secondary: '#C8102E', abbr: 'WSH' },
  'Winnipeg Jets': { primary: '#041E42', secondary: '#004C97', abbr: 'WPG' },
  'Phoenix Coyotes': { primary: '#8C2633', secondary: '#E2D6B5', abbr: 'PHX' },
  'Arizona Coyotes': { primary: '#8C2633', secondary: '#E2D6B5', abbr: 'ARI' },
  // ── MLB ──────────────────────────────────────────────────────────────────────
  'Arizona Diamondbacks': { primary: '#A71930', secondary: '#E3D4AD', abbr: 'ARI' },
  'Atlanta Braves': { primary: '#CE1141', secondary: '#13274F', abbr: 'ATL' },
  'Baltimore Orioles': { primary: '#DF4601', secondary: '#000000', abbr: 'BAL' },
  'Boston Red Sox': { primary: '#BD3039', secondary: '#0C2340', abbr: 'BOS' },
  'Chicago Cubs': { primary: '#0E3386', secondary: '#CC3433', abbr: 'CHC' },
  'Chicago White Sox': { primary: '#27251F', secondary: '#C4CED4', abbr: 'CWS' },
  'Cincinnati Reds': { primary: '#C6011F', secondary: '#000000', abbr: 'CIN' },
  'Cleveland Guardians': { primary: '#00385D', secondary: '#E31937', abbr: 'CLE' },
  'Colorado Rockies': { primary: '#33006F', secondary: '#C4CED4', abbr: 'COL' },
  'Detroit Tigers': { primary: '#0C2340', secondary: '#FA4616', abbr: 'DET' },
  'Houston Astros': { primary: '#002D62', secondary: '#EB6E1F', abbr: 'HOU' },
  'Kansas City Royals': { primary: '#004687', secondary: '#C09A5B', abbr: 'KC' },
  'Los Angeles Angels': { primary: '#BA0021', secondary: '#003263', abbr: 'LAA' },
  'Los Angeles Dodgers': { primary: '#005A9C', secondary: '#EF3E42', abbr: 'LAD' },
  'Miami Marlins': { primary: '#00A3E0', secondary: '#EF3340', abbr: 'MIA' },
  'Milwaukee Brewers': { primary: '#FFC52F', secondary: '#12284B', abbr: 'MIL' },
  'Minnesota Twins': { primary: '#002B5C', secondary: '#D31145', abbr: 'MIN' },
  'New York Mets': { primary: '#002D72', secondary: '#FF5910', abbr: 'NYM' },
  'New York Yankees': { primary: '#132448', secondary: '#C4CED4', abbr: 'NYY' },
  'Oakland Athletics': { primary: '#003831', secondary: '#EFB21E', abbr: 'OAK' },
  'Philadelphia Phillies': { primary: '#E81828', secondary: '#002D72', abbr: 'PHI' },
  'Pittsburgh Pirates': { primary: '#27251F', secondary: '#FDB827', abbr: 'PIT' },
  'San Diego Padres': { primary: '#2F241D', secondary: '#FFC425', abbr: 'SD' },
  'San Francisco Giants': { primary: '#FD5A1E', secondary: '#27251F', abbr: 'SF' },
  'Seattle Mariners': { primary: '#0C2C56', secondary: '#005C5C', abbr: 'SEA' },
  'St. Louis Cardinals': { primary: '#C41E3A', secondary: '#0C2340', abbr: 'STL' },
  'Tampa Bay Rays': { primary: '#092C5C', secondary: '#8FBCE6', abbr: 'TB' },
  'Texas Rangers': { primary: '#003278', secondary: '#C0111F', abbr: 'TEX' },
  'Toronto Blue Jays': { primary: '#134A8E', secondary: '#1D2D5C', abbr: 'TOR' },
  'Washington Nationals': { primary: '#AB0003', secondary: '#14225A', abbr: 'WSH' },
  'Cleveland Indians': { primary: '#00385D', secondary: '#E31937', abbr: 'CLE' },
  'Anaheim Angels': { primary: '#BA0021', secondary: '#003263', abbr: 'ANA' },
  'Montreal Expos': { primary: '#003087', secondary: '#E4002B', abbr: 'MON' },
}

const norm = (s: string) => s.normalize('NFD').replace(/\p{M}/gu, '').toLowerCase().replace(/[^a-z0-9 ]/g, ' ').replace(/\s+/g, ' ').trim()

/** Palette de l'equipe imprimee sur la carte (nom complet, ou dernier mot si non ambigu) ; null si inconnue */
export function teamPalette(name?: string | null): { primary: string; secondary: string } | null {
  const n = norm(name || '')
  if (!n) return null
  const entries = Object.entries(TEAM_COLORS)
  const exact = entries.find(([k]) => norm(k) === n)
  if (exact) return { primary: exact[1].primary, secondary: exact[1].secondary }
  const last = n.split(' ').slice(-1)[0]
  const m = entries.filter(([k]) => norm(k).split(' ').slice(-1)[0] === last)
  return m.length === 1 ? { primary: m[0][1].primary, secondary: m[0][1].secondary } : null
}
