'use client'
import { useState } from 'react'
import Link from 'next/link'

// Idees visuelles pour pousser la nouvelle DA (Surfquest, marine -> bleu electrique, angles droits, doubles filets, metaux).
// Page de TRAVAIL reservee aux admins : donnees d'exemple en dur, rien n'est lu ni ecrit.
// Serie 16 : galerie, visualiseur, fiche de carte, set, trades, messages, evenements, scanner, avec maquette. Tout le style est ici, prefixe .ix.

const SB = 'https://snnrkzbevjhdtviizfyp.supabase.co/storage/v1/object/public/avatars/cartes/eb730dee-414e-4fcb-89d8-4a7b3448c218/'
const C = {
  mccain: { nom: 'Jared McCain', img: SB + '1787763372857_recto.jpg' },
  edwards: { nom: 'Anthony Edwards', img: SB + '1784235265864_recto.jpg' },
  mcw: { nom: 'Michael Carter-Williams', img: SB + '1781875894817_recto.jpg' },
  maxey: { nom: 'Tyrese Maxey', img: SB + '1781291200820_recto.jpg' },
  hawkins: { nom: 'Hersey Hawkins', img: SB + '1781534889963_recto.jpg' },
  luwawu: { nom: 'Luwawu-Cabarrot', img: SB + 'csv_1790632470730_4f41x1.jpg' },
}

const CSS = `
.ix { font-family: system-ui, sans-serif; color:#fff; min-height:100vh;
  background: radial-gradient(circle at 15% -10%, rgba(91,141,239,.10), transparent 45%), linear-gradient(160deg,#050912 0%,#08153b 55%,#0a2468 100%); padding: 24px clamp(14px,3vw,44px) 90px; }
.ix * { box-sizing: border-box; }
.ix img { background: none !important; animation: none !important; }
.ix .sf { font-family: 'Surfquest', Impact, 'Arial Narrow', sans-serif; font-weight: 400; text-transform: uppercase; letter-spacing: .02em; }
.ix .ink, .ix .ink * { color: #06122e !important; }
.ix .wht, .ix .wht * { color: #fff !important; }
.ix h1 { font-size: clamp(34px,6vw,60px); margin: 8px 0 6px; line-height: .95; }
.ix .lead { max-width: 740px; color: rgba(255,255,255,.72); font-size: 15px; line-height: 1.5; margin: 0 0 30px; }
.ix .back { color:#fff; text-decoration:none; font-weight:800; font-size:13px; letter-spacing:.08em; text-transform:uppercase; }
.ix .bay { margin: 0 0 46px; max-width: 1180px; }
.ix .eyebrow { display:inline-block; padding:5px 14px; border:3px solid #fff; box-shadow: inset 0 0 0 3px #08153b, inset 0 0 0 4.5px #fff; font: 800 12px system-ui; letter-spacing:.18em; text-transform:uppercase; }
.ix .bay h2 { font-size: clamp(26px,4vw,40px); margin: 12px 0 6px; line-height: 1; }
.ix .bay p.d { color: rgba(255,255,255,.7); max-width: 700px; margin: 0 0 16px; font-size: 14px; line-height: 1.5; }
.ix .stage { border: 3px solid rgba(255,255,255,.22); background: linear-gradient(135deg,#050912 0%,#08153b 55%,#0a2468 100%); padding: clamp(16px,3vw,30px); position:relative; overflow:hidden; }
.ix .row { display:flex; gap: 24px; flex-wrap: wrap; align-items: flex-end; }
.ix .cap { font: 700 11px system-ui; letter-spacing:.14em; text-transform:uppercase; color: rgba(255,255,255,.55); margin-top: 10px; }
.ix .card { display:block; aspect-ratio: 2.5/3.5; object-fit: cover; border-radius: 0; box-shadow: 0 14px 30px rgba(0,0,0,.5); width:100%; }
.ix .btn { background:#fff; color:#06122e !important; border:3px solid #fff; padding: 8px 16px; font: 800 12px system-ui; letter-spacing:.1em; text-transform:uppercase; cursor:pointer; }
.ix .btn.o { background: transparent; color:#fff !important; }
.ix .tags { display:flex; flex-wrap:wrap; gap: 8px; margin: 0 0 30px; }
.ix .tags a { color:#fff; text-decoration:none; border: 2px solid rgba(255,255,255,.4); padding: 5px 10px; font: 800 10px system-ui; letter-spacing:.1em; text-transform:uppercase; }
.ix .tags a:hover { background:#fff; color:#06122e; }

/* serie 12 */
.ix .pnl { max-width: 560px; border: 3px solid #fff; } .ix .pnl > h4 { margin: 0; background:#fff; padding: 7px 14px; font-size: 20px; } .ix .pnl > h4, .ix .pnl > h4 * { color:#06122e !important; }
.ix .row2 { display:flex; align-items:center; gap: 12px; padding: 9px 14px; border-top: 1px solid rgba(255,255,255,.16); font-size: 14px; } .ix .row2 .n { width: 24px; font-size: 22px; } .ix .row2 .av { width: 30px; height: 30px; background:#2f6bff; display:flex; align-items:center; justify-content:center; font-size: 15px; } .ix .row2 b { flex:1; } .ix .row2 em { font-style:normal; font-weight:800; } .ix .row2 .up { color:#3ddc97 !important; font-size: 12px; font-weight:800; }
.ix .row2.me { background: rgba(255,255,255,.12); }
.ix .big { font-size: 44px; line-height: .9; } .ix .bar { height: 18px; background: rgba(255,255,255,.14); margin: 10px 0 6px; position:relative; } .ix .bar i { position:absolute; left:0; top:0; bottom:0; background:#fff; } .ix .sm { font: 700 11px system-ui; letter-spacing:.12em; text-transform:uppercase; opacity:.7; }
.ix .pad { padding: 14px; }
.ix .mini { display:flex; gap: 8px; } .ix .mini img { width: 64px; } .ix .grid4 { display:grid; grid-template-columns: repeat(4, 1fr); gap: 10px; } .ix .grid4 .c small { display:block; text-align:center; font: 700 10px system-ui; margin-top: 4px; opacity:.8; }
.ix .match { padding: 10px 14px; border-top: 1px solid rgba(255,255,255,.16); display:flex; gap: 12px; align-items:center; font-size: 13px; } .ix .match img { width: 38px; } .ix .match .gold { color:#ffd54a !important; font-weight:800; }
.ix .pin { border-left: 6px solid #ffd54a; background: rgba(255,213,74,.1); padding: 12px 16px; max-width: 560px; } .ix .pin .sm { color:#ffd54a !important; }
.ix .rsvp { display:flex; gap: 8px; margin-top: 10px; }
.ix .week { max-width: 560px; border: 3px solid #fff; padding: 16px; } .ix .week .k { display:grid; grid-template-columns: repeat(3,1fr); gap: 10px; margin: 12px 0; }
.ix .sv { display:flex; gap: 8px; flex-wrap:wrap; } .ix .sv span { border: 2px solid #fff; padding: 7px 14px; font: 800 12px system-ui; letter-spacing:.08em; text-transform:uppercase; } .ix .sv span.on { background:#fff; } .ix .sv span.on, .ix .sv span.on * { color:#06122e !important; } .ix .sv span.add { border-style: dashed; opacity:.7; }
.ix .tl { max-width: 520px; position:relative; padding-left: 22px; } .ix .tl:before { content:''; position:absolute; left: 6px; top: 6px; bottom: 6px; width: 3px; background:#fff; } .ix .tl .st { position:relative; padding: 0 0 16px; font-size: 14px; } .ix .tl .st:before { content:''; position:absolute; left:-22px; top: 4px; width: 15px; height: 15px; background:#06122e; border: 3px solid #fff; } .ix .tl .st.done:before { background:#fff; } .ix .tl .st small { display:block; opacity:.65; font-size: 12px; }
.ix .chart { max-width: 560px; border: 3px solid #fff; padding: 14px; } .ix .chart svg { width:100%; height: 120px; display:block; }
.ix .doc { display:flex; gap: 12px; align-items:center; padding: 10px 14px; border-top: 1px solid rgba(255,255,255,.16); } .ix .doc img { width: 44px; } .ix .doc .x2 { background:#ffd54a; padding: 2px 8px; font: 800 12px system-ui; } .ix .doc .x2, .ix .doc .x2 * { color:#06122e !important; }
.ix .two { display:grid; grid-template-columns: 1fr 1fr; max-width: 560px; border: 3px solid #fff; } .ix .two > div { padding: 12px 14px; } .ix .two > div + div { border-left: 1px solid rgba(255,255,255,.25); } .ix .two h5 { margin: 0 0 8px; font: 800 11px system-ui; letter-spacing:.14em; text-transform:uppercase; opacity:.7; }
.ix .bulkbar { max-width: 560px; background:#fff; display:flex; align-items:center; gap: 10px; padding: 10px 14px; flex-wrap:wrap; } .ix .bulkbar, .ix .bulkbar * { color:#06122e !important; } .ix .bulkbar b { font-size: 18px; margin-right: auto; } .ix .bulkbar span.b { border: 2px solid #06122e; padding: 5px 10px; font: 800 11px system-ui; letter-spacing:.08em; text-transform:uppercase; }
.ix .doc2 { max-width: 460px; background:#fff; padding: 18px; } .ix .doc2, .ix .doc2 * { color:#06122e !important; } .ix .doc2 .l { display:flex; justify-content:space-between; font-size: 12px; padding: 5px 0; border-bottom: 1px solid #ccd; } .ix .doc2 .t { display:flex; justify-content:space-between; margin-top: 10px; font-size: 26px; }
.ix .pcard { max-width: 560px; display:flex; gap: 14px; } .ix .pcard .info { flex:1; } .ix .own { font: 800 11px system-ui; letter-spacing:.1em; text-transform:uppercase; padding: 3px 8px; display:inline-block; margin-top: 6px; } .ix .own.y { background:#3ddc97; } .ix .own.y, .ix .own.y * { color:#06122e !important; } .ix .own.n { border: 2px solid #fff; }
.ix .roster12 { display:grid; grid-template-columns: repeat(5, 1fr); gap: 8px; max-width: 560px; } .ix .roster12 div { aspect-ratio: 1; display:flex; align-items:center; justify-content:center; border: 2px solid rgba(255,255,255,.3); font-size: 20px; } .ix .roster12 div.ok { background:#fff; } .ix .roster12 div.ok, .ix .roster12 div.ok * { color:#06122e !important; }
.ix .k3 { display:grid; grid-template-columns: repeat(3,1fr); gap: 10px; padding: 14px; } .ix .gold { color:#ffd54a !important; font-size: 12px; }
.ix .bar { max-width: 640px; }
/* serie 14 : maquettes du hero d'accueil */
.ix .hro { position: relative; max-width: 760px; height: 230px; border: 3px solid #fff; overflow: hidden; background: linear-gradient(135deg, #050912 0%, #0a2468 100%); }
.ix .hro .tx { position: relative; z-index: 3; padding: 20px 24px; }
.ix .hro .k { font: 800 11px system-ui; letter-spacing: .2em; }
.ix .hro .n { font-size: 84px; line-height: .9; margin: 14px 0 4px; }
.ix .hro .l { font: 800 11px system-ui; letter-spacing: .2em; }
.ix .hro .la { font-size: 12px; margin-top: 12px; }
.ix .hro:after { content: ''; position: absolute; inset: 0; z-index: 2; background: linear-gradient(90deg, rgba(5,9,18,.92) 0%, rgba(5,9,18,.55) 38%, transparent 70%); pointer-events: none; }
.ix .hro.h5:after, .ix .hro.h3:after { background: linear-gradient(90deg, rgba(5,9,18,.45) 0%, transparent 60%); }
.ix .hro .tiles { position: absolute; right: 0; top: 0; bottom: 0; width: 62%; display: grid; grid-template-columns: repeat(5, 1fr); gap: 6px; padding: 6px; overflow: hidden; z-index: 1; opacity: .85; }
.ix .hro .tiles img { width: 100%; aspect-ratio: 2.5/3.5; object-fit: cover; display: block; }
.ix .hro .tiles img:nth-child(5n+2) { margin-top: -34px; } .ix .hro .tiles img:nth-child(5n+4) { margin-top: -62px; } .ix .hro .tiles img:nth-child(5n+3) { margin-top: -12px; }
.ix .hro .big1 { position: absolute; right: 30px; top: -30px; width: 260px; aspect-ratio: 2.5/3.5; object-fit: cover; transform: rotate(8deg); box-shadow: 0 20px 50px rgba(0,0,0,.6); z-index: 1; }
.ix .hro .court { position: absolute; inset: 0; width: 100%; height: 100%; z-index: 1; }
.ix .hro .strip { position: absolute; left: 0; right: 0; bottom: 8px; height: 96px; overflow: hidden; z-index: 1; opacity: .5; }
.ix .hro .strip > div { display: flex; gap: 8px; width: max-content; }
.ix .hro .strip img { height: 96px; aspect-ratio: 2.5/3.5; object-fit: cover; display: block; }
.ix .hro.h5 { background: linear-gradient(100deg, #c8102e 0%, #1d428a 100%); }
.ix .hro .wm { position: absolute; right: 24px; top: -20px; font-size: 300px; line-height: 1; opacity: .22; z-index: 1; }
.ix .hro .pile { position: absolute; right: -20px; bottom: -60px; width: 330px; height: 300px; z-index: 1; }
.ix .hro .pile img { position: absolute; left: calc(var(--i) * 34px); bottom: calc(var(--i) * 4px); width: 130px; aspect-ratio: 2.5/3.5; object-fit: cover; transform: rotate(calc((var(--i) - 2) * 9deg)); box-shadow: 0 10px 28px rgba(0,0,0,.6); }
.ix .k4 { display: grid; grid-template-columns: repeat(4, 1fr); max-width: 620px; border: 3px solid #fff; } .ix .k4 > div { padding: 12px; text-align: center; border-right: 2px solid rgba(255,255,255,.22); } .ix .k4 > div:last-child { border-right: 0; } .ix .k4 b { display: block; font-size: 52px; line-height: .9; } .ix .k4 small { display: block; font: 800 11px system-ui; letter-spacing: .16em; margin-top: 4px; } .ix .k4 i { display: block; font-style: normal; font: 800 12px system-ui; color: #3ddc97 !important; min-height: 16px; margin-top: 2px; }
@media (max-width: 600px) { .ix .hro .n { font-size: 64px; }  .ix .hro .big1 { width: 190px; } .ix .hro .wm { font-size: 200px; } }
/* serie 15 */
.ix .hro.h7 { background: radial-gradient(ellipse at 75% 0%, #1b3a80 0%, #050912 70%); }
.ix .hro .spot { position: absolute; right: 90px; top: -20px; width: 340px; height: 300px; z-index: 1; background: conic-gradient(from 180deg at 50% 0%, transparent 150deg, rgba(255,235,170,.22) 180deg, transparent 210deg); }
.ix .hro .frames { position: absolute; right: 50px; top: 38px; z-index: 1; display: flex; gap: 14px; }
.ix .hro .frames img { width: 96px; aspect-ratio: 2.5/3.5; object-fit: cover; border: 3px solid #ffd54a; box-shadow: 0 0 0 3px #050912, 0 10px 24px rgba(0,0,0,.6); }
.ix .hro .holo { position: absolute; inset: 0; z-index: 1; background: linear-gradient(115deg, transparent 38%, rgba(255,90,160,.22) 44%, rgba(120,200,255,.28) 50%, rgba(140,255,170,.22) 56%, transparent 62%); }
.ix .hro .duo { position: absolute; inset: 0; width: 100%; height: 100%; object-fit: cover; object-position: 50% 25%; filter: grayscale(1) contrast(1.15); mix-blend-mode: screen; opacity: .45; z-index: 1; }
.ix .hro.h9 { background: #0a2fa8; }
.ix .hro .binder { position: absolute; right: 24px; top: 14px; z-index: 1; display: grid; grid-template-columns: repeat(4, 74px); gap: 8px; }
.ix .hro .binder > div { aspect-ratio: 2.5/3.5; border: 2px solid rgba(255,255,255,.22); background: rgba(255,255,255,.05); overflow: hidden; } .ix .hro .binder img { width: 100%; height: 100%; object-fit: cover; display: block; }
.ix .hro .amb { position: absolute; right: 70px; top: 28px; width: 130px; aspect-ratio: 2.5/3.5; object-fit: cover; z-index: 2; box-shadow: 0 14px 34px rgba(0,0,0,.6); }
.ix .hro .amb2 { position: absolute; right: -60px; top: -80px; width: 460px; aspect-ratio: 2.5/3.5; object-fit: cover; filter: blur(46px) saturate(1.5); opacity: .75; z-index: 1; }
.ix .hro .sky { position: absolute; inset: 0; z-index: 1; } .ix .hro .sky i { position: absolute; background: rgba(255,255,255,.75); border-radius: 50%; } .ix .hro .sky i.g { background: #ffd54a; box-shadow: 0 0 12px 3px rgba(255,213,74,.6); }
.ix .hdr { position: relative; max-width: 760px; height: 130px; border: 3px solid #fff; overflow: hidden; background: #050912; display: flex; flex-direction: column; justify-content: flex-end; padding: 16px 22px; } .ix .hdr .ph { position: absolute; inset: 0; display: flex; opacity: .32; } .ix .hdr .ph img { flex: 1; min-width: 0; object-fit: cover; object-position: 50% 30%; } .ix .hdr:after { content: ''; position: absolute; inset: 0; background: linear-gradient(90deg, #050912 15%, transparent); } .ix .hdr * { position: relative; z-index: 2; } .ix .hdr .ph, .ix .hdr .ph img { position: absolute; } .ix .hdr .ph img { position: relative; } .ix .hdr b { font-size: 46px; line-height: .9; }
.ix .ban { max-width: 560px; border: 3px solid #fff; background: #08153b; position: relative; padding-bottom: 14px; } .ix .ban .cv { height: 110px; overflow: hidden; } .ix .ban .cv img { width: 100%; height: 100%; object-fit: cover; object-position: 50% 30%; opacity: .75; } .ix .ban .av { width: 64px; height: 64px; border-radius: 50%; background: #2f6bff; border: 4px solid #08153b; margin: -32px 0 0 20px; display: flex; align-items: center; justify-content: center; font-size: 28px; } .ix .ban b { display: block; margin: 6px 20px 0; font-size: 30px; } .ix .ban small { margin: 0 20px; opacity: .7; }
.ix .team { max-width: 640px; border: 3px solid #fff; padding: 22px; display: flex; gap: 20px; align-items: center; background: linear-gradient(100deg, #c8102e, #1d428a); position: relative; overflow: hidden; } .ix .team .lg { font-size: 130px; line-height: .8; opacity: .3; } .ix .team b { display: block; font-size: 38px; line-height: .95; margin: 4px 0 10px; } .ix .team .k3t { display: flex; gap: 18px; flex-wrap: wrap; font-size: 12px; } .ix .team .k3t i { font-style: normal; font-size: 24px; display: block; line-height: 1; }
.ix .cover { position: relative; max-width: 640px; height: 170px; border: 3px solid #fff; overflow: hidden; } .ix .cover img { width: 100%; height: 100%; object-fit: cover; object-position: 50% 30%; opacity: .5; } .ix .cover .o { position: absolute; left: 20px; bottom: 16px; } .ix .cover b { display: block; font-size: 40px; line-height: .95; }
.ix .ld { display: flex; flex-direction: column; align-items: center; gap: 10px; padding: 20px; } .ix .ld .m { position: relative; font-size: 90px; line-height: 1; color: rgba(255,255,255,.2) !important; } .ix .ld .m i { position: absolute; left: 0; right: 0; bottom: 0; height: 62%; background: rgba(255,255,255,.9); mix-blend-mode: overlay; }
.ix .tex { max-width: 460px; padding: 24px; border: 3px solid #fff; background-color: #08153b; background-image: repeating-linear-gradient(45deg, rgba(255,255,255,.05) 0 1px, transparent 1px 7px); } .ix .tex b { display: block; font-size: 30px; } .ix .tex span { opacity: .7; font-size: 13px; }
.ix .tkt { position: relative; max-width: 520px; display: flex; align-items: center; gap: 14px; padding: 14px 22px; background: #0a0f20; border: 3px solid #fff; } .ix .tkt:before, .ix .tkt:after { content: ''; position: absolute; top: 50%; width: 22px; height: 22px; border-radius: 50%; background: #08153b; border: 3px solid #fff; transform: translateY(-50%); } .ix .tkt:before { left: -14px; } .ix .tkt:after { right: -14px; } .ix .tkt .side { display: flex; gap: 6px; } .ix .tkt .side img { width: 60px; aspect-ratio: 2.5/3.5; object-fit: cover; } .ix .tkt .mid { font-size: 34px; } .ix .tkt .stamp { position: absolute; right: 26px; bottom: 8px; border: 3px solid #ffd54a; color: #ffd54a !important; padding: 2px 8px; font-size: 16px; transform: rotate(-6deg); }
.ix .setc { display: flex; gap: 14px; align-items: center; max-width: 520px; border: 3px solid #fff; padding: 12px; } .ix .setc .cl { display: grid; grid-template-columns: 1fr 1fr; gap: 3px; width: 92px; flex-shrink: 0; } .ix .setc .cl img, .ix .setc .cl div { width: 100%; aspect-ratio: 2.5/3.5; object-fit: cover; background: rgba(255,255,255,.08); } .ix .setc b { display: block; font-size: 22px; line-height: 1; } .ix .setc .bar { max-width: none; margin: 8px 0 4px; }
/* serie 16 */
.ix .gdens { display: grid; gap: 6px; max-width: 560px; } .ix .gdens img { width: 100%; aspect-ratio: 2.5/3.5; object-fit: cover; display: block; }
.ix .peekw { position: relative; height: 210px; } .ix .peek { position: absolute; left: 60px; top: 20px; width: 300px; display: flex; gap: 12px; padding: 12px; background: #fff; box-shadow: 0 16px 40px rgba(0,0,0,.6); } .ix .peek, .ix .peek * { color: #06122e !important; } .ix .peek img { width: 110px; aspect-ratio: 2.5/3.5; object-fit: cover; } .ix .peek b { display: block; font-size: 22px; line-height: 1; } .ix .peek small { display: block; font-size: 11px; margin: 4px 0 8px; } .ix .peek .gold { font: 800 13px system-ui; }
.ix .sep { max-width: 520px; } .ix .sep .sh { display: flex; align-items: baseline; gap: 12px; padding: 8px 12px; background: #fff; margin: 8px 0; } .ix .sep .sh, .ix .sep .sh * { color: #06122e !important; } .ix .sep .sh b { font-size: 22px; } .ix .sep .sh span { flex: 1; font: 700 12px system-ui; } .ix .sep .sh i { font-style: normal; }
.ix .draw { display: flex; gap: 16px; max-width: 560px; border: 3px solid #fff; padding: 14px; } .ix .draw .dp { flex: 1; min-width: 0; }
.ix .ibar { display: inline-flex; border: 3px solid #fff; } .ix .ibar > div { padding: 10px 18px; text-align: center; border-right: 2px solid rgba(255,255,255,.3); cursor: pointer; } .ix .ibar > div:last-child { border-right: 0; } .ix .ibar b { display: block; font-size: 20px; } .ix .ibar small { font: 800 10px system-ui; letter-spacing: .1em; text-transform: uppercase; } .ix .ibar .red, .ix .ibar .red * { color: #ff6b6f !important; }
.ix .fiche { display: flex; gap: 16px; max-width: 520px; border: 3px solid #fff; padding: 14px; } .ix .fiche .nav { display: flex; gap: 14px; align-items: center; margin-top: 12px; font: 800 12px system-ui; } .ix .fiche .nav span { border: 2px solid rgba(255,255,255,.5); padding: 3px 9px; }
.ix .sil { display: grid; grid-template-columns: repeat(6, 1fr); gap: 8px; max-width: 520px; } .ix .sil > div { aspect-ratio: 2.5/3.5; border: 2px solid rgba(255,255,255,.2); background: rgba(255,255,255,.05); display: flex; align-items: center; justify-content: center; overflow: hidden; } .ix .sil > div.ok { border-color: #fff; } .ix .sil img { width: 100%; height: 100%; object-fit: cover; display: block; } .ix .sil span { font-size: 22px; opacity: .3; }
.ix .stick { max-width: 560px; border: 3px solid #fff; padding: 12px 14px; background: #0a0f20; }
.ix .bal { max-width: 520px; } .ix .scale { position: relative; height: 6px; background: rgba(255,255,255,.2); margin: 14px 0 10px; } .ix .scale:before { content: ''; position: absolute; left: 50%; top: -6px; width: 2px; height: 18px; background: #fff; } .ix .scale i { position: absolute; top: -7px; width: 20px; height: 20px; background: #3ddc97; margin-left: -10px; }
.ix .stampx { display: inline-block; border: 4px solid #3ddc97; padding: 10px 18px; transform: rotate(-3deg); } .ix .stampx, .ix .stampx * { color: #3ddc97 !important; } .ix .stampx b { display: block; font-size: 30px; line-height: 1; } .ix .stampx span { font: 800 11px system-ui; letter-spacing: .1em; text-transform: uppercase; }
.ix .cal { max-width: 360px; border: 3px solid #fff; } .ix .cal .ch { background: #fff; padding: 8px 14px; font-size: 20px; } .ix .cal .ch, .ix .cal .ch * { color: #06122e !important; } .ix .cal .cg { display: grid; grid-template-columns: repeat(7, 1fr); } .ix .cal .cg > div { aspect-ratio: 1; display: flex; align-items: center; justify-content: center; font-size: 13px; border: 1px solid rgba(255,255,255,.1); position: relative; } .ix .cal .cg .ev { background: #ffd54a; } .ix .cal .cg .ev, .ix .cal .cg .ev * { color: #06122e !important; font-weight: 800; } .ix .cal .cg .now { outline: 2px solid #fff; outline-offset: -3px; }
.ix .conf2 { max-width: 440px; border: 3px solid #fff; } .ix .conf2 .f { display: flex; align-items: center; gap: 12px; padding: 10px 14px; border-bottom: 1px solid rgba(255,255,255,.15); } .ix .conf2 .f i { width: 12px; height: 12px; border-radius: 50%; background: #3ddc97; } .ix .conf2 .f.o i { background: #ffb020; } .ix .conf2 .f.r i { background: #ff5a5f; } .ix .conf2 .f.o, .ix .conf2 .f.r { background: rgba(255,176,32,.1); } .ix .conf2 .f span { width: 90px; font: 700 11px system-ui; letter-spacing: .1em; text-transform: uppercase; opacity: .7; } .ix .conf2 .f b { font-size: 15px; }
.ix .help { position: relative; max-width: 420px; } .ix .help i { display: inline-flex; align-items: center; justify-content: center; width: 22px; height: 22px; border: 2px solid #fff; border-radius: 50%; font: 800 13px system-ui; font-style: normal; margin-left: 6px; } .ix .help .hb { margin-top: 10px; padding: 12px 14px; background: #fff; font-size: 13px; line-height: 1.4; } .ix .help .hb, .ix .help .hb * { color: #06122e !important; }
.ix .story { width: 220px; aspect-ratio: 9/16; border: 3px solid #fff; padding: 18px 14px; display: flex; flex-direction: column; align-items: center; gap: 4px; text-align: center; background: linear-gradient(160deg, #050912, #0a2468); } .ix .story .n { font-size: 76px; line-height: .9; } .ix .story .mini { margin: 10px 0; gap: 5px; } .ix .story .mini img { width: 54px; }
`
function Bay({ id, n, title, desc, children }: { id: string; n: string; title: string; desc: string; children: React.ReactNode }) {
  return (
    <section className="bay" id={id}>
      <span className="eyebrow">{n}</span>
      <h2 className="sf">{title}</h2>
      <p className="d">{desc}</p>
      <div className="stage">{children}</div>
    </section>
  )
}

const ALL = [C.mccain, C.edwards, C.maxey, C.hawkins, C.mcw, C.luwawu]

export default function DaIdeas() {
  const [dens, setDens] = useState(4)
  const [chip, setChip] = useState(0)
  const names = ['Densité de grille', 'Aperçu rapide', 'Séparateurs par année', 'Barre de filtres collante', 'Tiroir du visualiseur', 'Actions en icônes', 'Fiche de carte publique', 'Set en silhouettes', 'Barre de set collante', 'Échange équilibré', 'Réputation', 'Réponses rapides', 'Calendrier d’événements', 'Confiance du scan', 'Aide contextuelle', 'Story partageable']
  return (
    <div className="ix">
      <style>{CSS}</style>
      <Link href="/admin" className="back">← Admin</Link>
      <h1 className="sf">Idées · Série 16</h1>
      <p className="lead">Seize idées sur des pages encore intactes : galerie, visualiseur, fiche de carte, détail d&apos;un set, échanges, messages, événements, scanner. Dis-moi les numéros à faire.</p>
      <nav className="tags">{names.map((t, i) => <a key={t} href={`#s${i + 1}`}>{String(i + 1).padStart(2, '0')} {t}</a>)}</nav>

      <Bay id="s1" n="01 — Galerie" title="Une densité de grille réglable" desc="Un petit curseur à 3 crans au-dessus de la grille : cartes grandes (3 par ligne), moyennes (5) ou toutes petites (8) pour parcourir 600 cartes d'un coup d'œil. Le choix est mémorisé sur l'appareil."><div className="wht"><div className="sv" style={{ marginBottom: 12 }}>{[3, 5, 8].map(n => <span key={n} className={dens === n ? 'on' : ''} onClick={() => setDens(n)}>{n} par ligne</span>)}</div><div className="gdens" style={{ gridTemplateColumns: `repeat(${dens}, 1fr)` }}>{Array.from({ length: dens * 2 }, (_, i) => <img key={i} src={ALL[i % 6].img} alt="" />)}</div></div></Bay>
      <Bay id="s2" n="02 — Galerie" title="Un aperçu rapide au maintien" desc="Un appui long (ou un survol prolongé sur ordinateur) sur une vignette l'agrandit en bulle avec la désignation, le tirage et la valeur, sans ouvrir le visualiseur. On inspecte vite sans quitter la grille."><div className="peekw wht"><img className="card" style={{ width: 90 }} src={C.maxey.img} alt="" /><div className="peek"><img src={C.maxey.img} alt="" /><div><b className="sf">Tyrese Maxey</b><small>2020-21 Court Kings RC</small><span className="gold">/149 · 38 €</span></div></div></div></Bay>
      <Bay id="s3" n="03 — Galerie" title="Des séparateurs par année ou par collection" desc="En tri par année ou par collection, la grille se découpe avec des bandeaux collants « 2024-25 · 34 cartes ». On sait où on est dans une longue collection, et on peut replier une section."><div className="sep wht"><div className="sh"><b className="sf">2024-25</b><span>34 cartes</span><i>▾</i></div><div className="mini">{ALL.slice(0, 4).map(c => <img key={c.nom} className="card" style={{ width: 70 }} src={c.img} alt="" />)}</div><div className="sh"><b className="sf">2023-24</b><span>51 cartes</span><i>▸</i></div></div></Bay>
      <Bay id="s4" n="04 — Galerie" title="Une barre de filtres collante avec les filtres actifs" desc="En défilant, la barre de recherche et de tri reste en haut avec le nombre de résultats et les filtres actifs en puces à retirer d'un clic (« RC ✕ », « 2024 ✕ »). Fini de remonter en haut pour ajuster."><div className="chips wht"><span className="on">RC <b>✕</b></span><span className="on">2024-25 <b>✕</b></span><span className="on">/99 et moins <b>✕</b></span><span style={{ borderStyle: 'dashed', opacity: .7 }}>12 résultats · Effacer</span></div></Bay>
      <Bay id="s5" n="05 — Visualiseur" title="Les infos du visualiseur en tiroir à onglets" desc="À côté de la carte en 3D, un tiroir avec quatre onglets : Détails, Valeur, Histoire, Commentaires. Aujourd'hui tout est empilé dans une longue colonne. Sur mobile, le tiroir monte du bas."><div className="draw wht"><img className="card" style={{ width: 120 }} src={C.mccain.img} alt="" /><div className="dp"><div className="sv" style={{ marginBottom: 10 }}><span className="on">Détails</span><span>Valeur</span><span>Histoire</span><span>Com. 3</span></div><div className="row2"><b>Collection</b><em>Contenders</em></div><div className="row2"><b>Tirage</b><em>/149</em></div><div className="row2"><b>Numéro</b><em>#12</em></div></div></div></Bay>
      <Bay id="s6" n="06 — Visualiseur" title="Les actions en barre d'icônes" desc="Partager, mettre en vente, modifier, supprimer : quatre icônes carrées avec une légende courte, en bas du visualiseur, à la place des gros boutons empilés. Supprimer reste en rouge et demande confirmation."><div className="ibar wht">{[['🔗', 'Partager'], ['🏷', 'Vendre'], ['✏️', 'Modifier'], ['🗑', 'Supprimer']].map(a => <div key={a[1]} className={a[1] === 'Supprimer' ? 'red' : ''}><b>{a[0]}</b><small>{a[1]}</small></div>)}</div></Bay>
      <Bay id="s7" n="07 — Fiche publique" title="Une fiche de carte avec sa place dans le set" desc="Sur la page publique d'une carte : la photo, la désignation Beckett, « #12 sur 300 · 2024-25 Contenders » avec flèches carte précédente / suivante du set, et « 3 autres collectionneurs l'ont ». Plus riche pour Google et pour les visiteurs."><div className="fiche wht"><img className="card" style={{ width: 130 }} src={C.mccain.img} alt="" /><div><span className="sm">2024-25 Panini Contenders</span><b className="sf" style={{ display: 'block', fontSize: 28, lineHeight: 1 }}>Jared McCain RC</b><div className="nav"><span>‹ #11</span><b>#12 / 300</b><span>#13 ›</span></div><div className="sm" style={{ marginTop: 10 }}>3 autres collectionneurs · valeur 45 €</div></div></div></Bay>
      <Bay id="s8" n="08 — Setlist" title="Un set en silhouettes : possédées en couleur, manquantes en gris" desc="Dans le détail d'un set, une vue grille où chaque carte du set a sa case : en couleur avec la photo si tu l'as, en silhouette grisée avec le numéro sinon. On voit les trous d'un coup d'œil, comme dans un classeur."><div className="sil wht">{Array.from({ length: 12 }, (_, i) => <div key={i} className={[0, 1, 3, 4, 7, 9].includes(i) ? 'ok' : ''}>{[0, 1, 3, 4, 7, 9].includes(i) ? <img src={ALL[i % 6].img} alt="" /> : <span className="sf">#{i + 1}</span>}</div>)}</div></Bay>
      <Bay id="s9" n="09 — Setlist" title="Une barre de progression de set collante" desc="En haut d'un long set : la jauge reste visible avec « 288 / 300 · il manque 12 » et un bouton « Voir les manquantes » qui filtre la liste d'un clic. Le but reste toujours sous les yeux."><div className="stick wht"><b className="sf">2024-25 Panini Select</b><div className="bar" style={{ margin: '6px 0' }}><i style={{ width: '96%' }} /></div><div className="row2" style={{ border: 0, padding: 0 }}><span>288 / 300 · <b>il manque 12</b></span><button className="btn o" style={{ padding: '4px 10px' }}>Voir les manquantes</button></div></div></Bay>
      <Bay id="s10" n="10 — Trades" title="Un échange équilibré avec la balance de valeur" desc="À la création d'un échange : deux colonnes « Je donne » et « Je reçois », et en bas une balance qui penche d'un côté avec l'écart (« +8 € pour toi »). Ça évite les échanges déséquilibrés sans calculer à la main."><div className="bal wht"><div className="two" style={{ maxWidth: 'none' }}><div><h5>Je donne · 42 €</h5><div className="mini"><img className="card" src={C.edwards.img} alt="" /></div></div><div><h5>Je reçois · 50 €</h5><div className="mini"><img className="card" src={C.maxey.img} alt="" /></div></div></div><div className="scale"><i style={{ left: '58%' }} /></div><div className="sm" style={{ textAlign: 'center' }}>Écart : +8 € pour toi</div></div></Bay>
      <Bay id="s11" n="11 — Profil" title="Un tampon de réputation d'échange" desc="Sur le profil et les offres : un tampon « 12 échanges · 100 % réussis » avec un niveau de confiance (Nouveau, Fiable, Très fiable). Aujourd'hui la réputation existe mais n'est pas assez visible au moment de décider d'échanger."><div className="stampx wht"><b className="sf">Très fiable</b><span>12 échanges · 100 % réussis · membre depuis 2025</span></div></Bay>
      <Bay id="s12" n="12 — Messages" title="Des réponses rapides dans la messagerie" desc="Au-dessus du clavier, des puces cliquables adaptées au contexte : « Toujours dispo ? », « Dernier prix ? », « Je te propose un échange », « Merci ! ». Gagne du temps, surtout sur mobile."><div className="chips wht">{['Toujours dispo ?', 'Dernier prix ?', 'Je te propose un échange', 'Merci !'].map((t, i) => <span key={t} className={chip === i ? 'on' : ''} onClick={() => setChip(i)}>{t}</span>)}</div></Bay>
      <Bay id="s13" n="13 — Événements" title="Un calendrier mensuel des événements" desc="Une grille de mois avec un point doré sur les jours d'événement (salons, lives, concours), et la liste du jour en dessous. On voit les dates d'un coup d'œil au lieu d'une liste chronologique."><div className="cal wht"><div className="ch sf">Octobre 2026</div><div className="cg">{Array.from({ length: 31 }, (_, i) => <div key={i} className={i + 1 === 18 ? 'ev' : i + 1 === 10 ? 'now' : ''}>{i + 1}</div>)}</div></div></Bay>
      <Bay id="s14" n="14 — Scanner" title="Une jauge de confiance sur chaque champ du scan" desc="Après un scan, chaque champ pré-rempli (joueur, année, collection, numéro) a un petit voyant vert, orange ou rouge selon la certitude de la lecture, et les champs douteux sont surlignés pour être vérifiés d'abord. On corrige en quelques secondes."><div className="conf2 wht">{([['Joueur', 'Jared McCain', 'g'], ['Année', '2024-25', 'g'], ['Collection', 'Contenders', 'o'], ['Numéro', '#12', 'r']] as [string, string, string][]).map(f => <div key={f[0]} className={'f ' + f[2]}><i /><span>{f[0]}</span><b>{f[1]}</b></div>)}</div></Bay>
      <Bay id="s15" n="15 — Aide" title="Des bulles d'aide contextuelles" desc="Un petit « ? » discret à côté des fonctions complexes (import TCDB, synchro de setlist, PC équipe) qui ouvre une bulle de deux lignes avec un exemple. Remplace le long tutoriel pour les nouveaux."><div className="help wht"><b className="sf" style={{ fontSize: 22 }}>Importer depuis TCDB <i>?</i></b><div className="hb">Sur TCDB, ouvre ta collection, clique sur <b>Print</b>, enregistre en PDF puis dépose-le ici.</div></div></Bay>
      <Bay id="s16" n="16 — Partage" title="Une story partageable de ta collection" desc="Un bouton « Partager ma collection » qui génère une image verticale (format story) avec ton pseudo, le total, tes RC / AUTO / PATCH et trois de tes plus belles cartes. Prête pour Instagram, Discord ou X."><div className="story wht"><b className="sf">GKNNN_CARDS</b><div className="n sf">599</div><span className="sm">CARTES</span><div className="mini">{[C.mccain, C.edwards, C.maxey].map(c => <img key={c.nom} className="card" src={c.img} alt="" />)}</div><small>RC 119 · AUTO 29 · PATCH 23</small></div></Bay>
    </div>
  )
}
