'use client'
import { useState } from 'react'
import Link from 'next/link'

// Idees visuelles pour pousser la nouvelle DA (Surfquest, marine -> bleu electrique, angles droits, doubles filets, metaux).
// Page de TRAVAIL reservee aux admins : donnees d'exemple en dur, rien n'est lu ni ecrit.
// Serie 17 : visualiseur de carte (panneau, mobile, scene), avec maquette. Tout le style est ici, prefixe .ix.

const SB = 'https://snnrkzbevjhdtviizfyp.supabase.co/storage/v1/object/public/avatars/cartes/eb730dee-414e-4fcb-89d8-4a7b3448c218/'
const C = {
  mccain: { nom: 'Jared McCain', img: SB + '1787763372857_recto.jpg' },
  edwards: { nom: 'Anthony Edwards', img: SB + '1784235265864_recto.jpg' },
  mcw: { nom: 'Michael Carter-Williams', img: SB + '1781875894817_recto.jpg' },
  maxey: { nom: 'Tyrese Maxey', img: SB + '1781291200820_recto.jpg' },
  hawkins: { nom: 'Hersey Hawkins', img: SB + '1781534889963_recto.jpg' },
  luwawu: { nom: 'Luwawu-Cabarrot', img: SB + 'csv_1790632470730_4f41x1.jpg' },
}

const CSS = `
.ix { font-family: system-ui, sans-serif; color:#fff; min-height:100vh;
  background: radial-gradient(circle at 15% -10%, rgba(91,141,239,.10), transparent 45%), linear-gradient(160deg,#050912 0%,#08153b 55%,#0a2468 100%); padding: 24px clamp(14px,3vw,44px) 90px; }
.ix * { box-sizing: border-box; }
.ix img { background: none !important; animation: none !important; }
.ix .sf { font-family: 'Surfquest', Impact, 'Arial Narrow', sans-serif; font-weight: 400; text-transform: uppercase; letter-spacing: .02em; }
.ix .ink, .ix .ink * { color: #06122e !important; }
.ix .wht, .ix .wht * { color: #fff !important; }
.ix h1 { font-size: clamp(34px,6vw,60px); margin: 8px 0 6px; line-height: .95; }
.ix .lead { max-width: 740px; color: rgba(255,255,255,.72); font-size: 15px; line-height: 1.5; margin: 0 0 30px; }
.ix .back { color:#fff; text-decoration:none; font-weight:800; font-size:13px; letter-spacing:.08em; text-transform:uppercase; }
.ix .bay { margin: 0 0 46px; max-width: 1180px; }
.ix .eyebrow { display:inline-block; padding:5px 14px; border:3px solid #fff; box-shadow: inset 0 0 0 3px #08153b, inset 0 0 0 4.5px #fff; font: 800 12px system-ui; letter-spacing:.18em; text-transform:uppercase; }
.ix .bay h2 { font-size: clamp(26px,4vw,40px); margin: 12px 0 6px; line-height: 1; }
.ix .bay p.d { color: rgba(255,255,255,.7); max-width: 700px; margin: 0 0 16px; font-size: 14px; line-height: 1.5; }
.ix .stage { border: 3px solid rgba(255,255,255,.22); background: linear-gradient(135deg,#050912 0%,#08153b 55%,#0a2468 100%); padding: clamp(16px,3vw,30px); position:relative; overflow:hidden; }
.ix .row { display:flex; gap: 24px; flex-wrap: wrap; align-items: flex-end; }
.ix .cap { font: 700 11px system-ui; letter-spacing:.14em; text-transform:uppercase; color: rgba(255,255,255,.55); margin-top: 10px; }
.ix .card { display:block; aspect-ratio: 2.5/3.5; object-fit: cover; border-radius: 0; box-shadow: 0 14px 30px rgba(0,0,0,.5); width:100%; }
.ix .btn { background:#fff; color:#06122e !important; border:3px solid #fff; padding: 8px 16px; font: 800 12px system-ui; letter-spacing:.1em; text-transform:uppercase; cursor:pointer; }
.ix .btn.o { background: transparent; color:#fff !important; }
.ix .tags { display:flex; flex-wrap:wrap; gap: 8px; margin: 0 0 30px; }
.ix .tags a { color:#fff; text-decoration:none; border: 2px solid rgba(255,255,255,.4); padding: 5px 10px; font: 800 10px system-ui; letter-spacing:.1em; text-transform:uppercase; }
.ix .tags a:hover { background:#fff; color:#06122e; }

/* serie 12 */
.ix .pnl { max-width: 560px; border: 3px solid #fff; } .ix .pnl > h4 { margin: 0; background:#fff; padding: 7px 14px; font-size: 20px; } .ix .pnl > h4, .ix .pnl > h4 * { color:#06122e !important; }
.ix .row2 { display:flex; align-items:center; gap: 12px; padding: 9px 14px; border-top: 1px solid rgba(255,255,255,.16); font-size: 14px; } .ix .row2 .n { width: 24px; font-size: 22px; } .ix .row2 .av { width: 30px; height: 30px; background:#2f6bff; display:flex; align-items:center; justify-content:center; font-size: 15px; } .ix .row2 b { flex:1; } .ix .row2 em { font-style:normal; font-weight:800; } .ix .row2 .up { color:#3ddc97 !important; font-size: 12px; font-weight:800; }
.ix .row2.me { background: rgba(255,255,255,.12); }
.ix .big { font-size: 44px; line-height: .9; } .ix .bar { height: 18px; background: rgba(255,255,255,.14); margin: 10px 0 6px; position:relative; } .ix .bar i { position:absolute; left:0; top:0; bottom:0; background:#fff; } .ix .sm { font: 700 11px system-ui; letter-spacing:.12em; text-transform:uppercase; opacity:.7; }
.ix .pad { padding: 14px; }
.ix .mini { display:flex; gap: 8px; } .ix .mini img { width: 64px; } .ix .grid4 { display:grid; grid-template-columns: repeat(4, 1fr); gap: 10px; } .ix .grid4 .c small { display:block; text-align:center; font: 700 10px system-ui; margin-top: 4px; opacity:.8; }
.ix .match { padding: 10px 14px; border-top: 1px solid rgba(255,255,255,.16); display:flex; gap: 12px; align-items:center; font-size: 13px; } .ix .match img { width: 38px; } .ix .match .gold { color:#ffd54a !important; font-weight:800; }
.ix .pin { border-left: 6px solid #ffd54a; background: rgba(255,213,74,.1); padding: 12px 16px; max-width: 560px; } .ix .pin .sm { color:#ffd54a !important; }
.ix .rsvp { display:flex; gap: 8px; margin-top: 10px; }
.ix .week { max-width: 560px; border: 3px solid #fff; padding: 16px; } .ix .week .k { display:grid; grid-template-columns: repeat(3,1fr); gap: 10px; margin: 12px 0; }
.ix .sv { display:flex; gap: 8px; flex-wrap:wrap; } .ix .sv span { border: 2px solid #fff; padding: 7px 14px; font: 800 12px system-ui; letter-spacing:.08em; text-transform:uppercase; } .ix .sv span.on { background:#fff; } .ix .sv span.on, .ix .sv span.on * { color:#06122e !important; } .ix .sv span.add { border-style: dashed; opacity:.7; }
.ix .tl { max-width: 520px; position:relative; padding-left: 22px; } .ix .tl:before { content:''; position:absolute; left: 6px; top: 6px; bottom: 6px; width: 3px; background:#fff; } .ix .tl .st { position:relative; padding: 0 0 16px; font-size: 14px; } .ix .tl .st:before { content:''; position:absolute; left:-22px; top: 4px; width: 15px; height: 15px; background:#06122e; border: 3px solid #fff; } .ix .tl .st.done:before { background:#fff; } .ix .tl .st small { display:block; opacity:.65; font-size: 12px; }
.ix .chart { max-width: 560px; border: 3px solid #fff; padding: 14px; } .ix .chart svg { width:100%; height: 120px; display:block; }
.ix .doc { display:flex; gap: 12px; align-items:center; padding: 10px 14px; border-top: 1px solid rgba(255,255,255,.16); } .ix .doc img { width: 44px; } .ix .doc .x2 { background:#ffd54a; padding: 2px 8px; font: 800 12px system-ui; } .ix .doc .x2, .ix .doc .x2 * { color:#06122e !important; }
.ix .two { display:grid; grid-template-columns: 1fr 1fr; max-width: 560px; border: 3px solid #fff; } .ix .two > div { padding: 12px 14px; } .ix .two > div + div { border-left: 1px solid rgba(255,255,255,.25); } .ix .two h5 { margin: 0 0 8px; font: 800 11px system-ui; letter-spacing:.14em; text-transform:uppercase; opacity:.7; }
.ix .bulkbar { max-width: 560px; background:#fff; display:flex; align-items:center; gap: 10px; padding: 10px 14px; flex-wrap:wrap; } .ix .bulkbar, .ix .bulkbar * { color:#06122e !important; } .ix .bulkbar b { font-size: 18px; margin-right: auto; } .ix .bulkbar span.b { border: 2px solid #06122e; padding: 5px 10px; font: 800 11px system-ui; letter-spacing:.08em; text-transform:uppercase; }
.ix .doc2 { max-width: 460px; background:#fff; padding: 18px; } .ix .doc2, .ix .doc2 * { color:#06122e !important; } .ix .doc2 .l { display:flex; justify-content:space-between; font-size: 12px; padding: 5px 0; border-bottom: 1px solid #ccd; } .ix .doc2 .t { display:flex; justify-content:space-between; margin-top: 10px; font-size: 26px; }
.ix .pcard { max-width: 560px; display:flex; gap: 14px; } .ix .pcard .info { flex:1; } .ix .own { font: 800 11px system-ui; letter-spacing:.1em; text-transform:uppercase; padding: 3px 8px; display:inline-block; margin-top: 6px; } .ix .own.y { background:#3ddc97; } .ix .own.y, .ix .own.y * { color:#06122e !important; } .ix .own.n { border: 2px solid #fff; }
.ix .roster12 { display:grid; grid-template-columns: repeat(5, 1fr); gap: 8px; max-width: 560px; } .ix .roster12 div { aspect-ratio: 1; display:flex; align-items:center; justify-content:center; border: 2px solid rgba(255,255,255,.3); font-size: 20px; } .ix .roster12 div.ok { background:#fff; } .ix .roster12 div.ok, .ix .roster12 div.ok * { color:#06122e !important; }
.ix .k3 { display:grid; grid-template-columns: repeat(3,1fr); gap: 10px; padding: 14px; } .ix .gold { color:#ffd54a !important; font-size: 12px; }
.ix .bar { max-width: 640px; }
/* serie 14 : maquettes du hero d'accueil */
.ix .hro { position: relative; max-width: 760px; height: 230px; border: 3px solid #fff; overflow: hidden; background: linear-gradient(135deg, #050912 0%, #0a2468 100%); }
.ix .hro .tx { position: relative; z-index: 3; padding: 20px 24px; }
.ix .hro .k { font: 800 11px system-ui; letter-spacing: .2em; }
.ix .hro .n { font-size: 84px; line-height: .9; margin: 14px 0 4px; }
.ix .hro .l { font: 800 11px system-ui; letter-spacing: .2em; }
.ix .hro .la { font-size: 12px; margin-top: 12px; }
.ix .hro:after { content: ''; position: absolute; inset: 0; z-index: 2; background: linear-gradient(90deg, rgba(5,9,18,.92) 0%, rgba(5,9,18,.55) 38%, transparent 70%); pointer-events: none; }
.ix .hro.h5:after, .ix .hro.h3:after { background: linear-gradient(90deg, rgba(5,9,18,.45) 0%, transparent 60%); }
.ix .hro .tiles { position: absolute; right: 0; top: 0; bottom: 0; width: 62%; display: grid; grid-template-columns: repeat(5, 1fr); gap: 6px; padding: 6px; overflow: hidden; z-index: 1; opacity: .85; }
.ix .hro .tiles img { width: 100%; aspect-ratio: 2.5/3.5; object-fit: cover; display: block; }
.ix .hro .tiles img:nth-child(5n+2) { margin-top: -34px; } .ix .hro .tiles img:nth-child(5n+4) { margin-top: -62px; } .ix .hro .tiles img:nth-child(5n+3) { margin-top: -12px; }
.ix .hro .big1 { position: absolute; right: 30px; top: -30px; width: 260px; aspect-ratio: 2.5/3.5; object-fit: cover; transform: rotate(8deg); box-shadow: 0 20px 50px rgba(0,0,0,.6); z-index: 1; }
.ix .hro .court { position: absolute; inset: 0; width: 100%; height: 100%; z-index: 1; }
.ix .hro .strip { position: absolute; left: 0; right: 0; bottom: 8px; height: 96px; overflow: hidden; z-index: 1; opacity: .5; }
.ix .hro .strip > div { display: flex; gap: 8px; width: max-content; }
.ix .hro .strip img { height: 96px; aspect-ratio: 2.5/3.5; object-fit: cover; display: block; }
.ix .hro.h5 { background: linear-gradient(100deg, #c8102e 0%, #1d428a 100%); }
.ix .hro .wm { position: absolute; right: 24px; top: -20px; font-size: 300px; line-height: 1; opacity: .22; z-index: 1; }
.ix .hro .pile { position: absolute; right: -20px; bottom: -60px; width: 330px; height: 300px; z-index: 1; }
.ix .hro .pile img { position: absolute; left: calc(var(--i) * 34px); bottom: calc(var(--i) * 4px); width: 130px; aspect-ratio: 2.5/3.5; object-fit: cover; transform: rotate(calc((var(--i) - 2) * 9deg)); box-shadow: 0 10px 28px rgba(0,0,0,.6); }
.ix .k4 { display: grid; grid-template-columns: repeat(4, 1fr); max-width: 620px; border: 3px solid #fff; } .ix .k4 > div { padding: 12px; text-align: center; border-right: 2px solid rgba(255,255,255,.22); } .ix .k4 > div:last-child { border-right: 0; } .ix .k4 b { display: block; font-size: 52px; line-height: .9; } .ix .k4 small { display: block; font: 800 11px system-ui; letter-spacing: .16em; margin-top: 4px; } .ix .k4 i { display: block; font-style: normal; font: 800 12px system-ui; color: #3ddc97 !important; min-height: 16px; margin-top: 2px; }
@media (max-width: 600px) { .ix .hro .n { font-size: 64px; }  .ix .hro .big1 { width: 190px; } .ix .hro .wm { font-size: 200px; } }
/* serie 15 */
.ix .hro.h7 { background: radial-gradient(ellipse at 75% 0%, #1b3a80 0%, #050912 70%); }
.ix .hro .spot { position: absolute; right: 90px; top: -20px; width: 340px; height: 300px; z-index: 1; background: conic-gradient(from 180deg at 50% 0%, transparent 150deg, rgba(255,235,170,.22) 180deg, transparent 210deg); }
.ix .hro .frames { position: absolute; right: 50px; top: 38px; z-index: 1; display: flex; gap: 14px; }
.ix .hro .frames img { width: 96px; aspect-ratio: 2.5/3.5; object-fit: cover; border: 3px solid #ffd54a; box-shadow: 0 0 0 3px #050912, 0 10px 24px rgba(0,0,0,.6); }
.ix .hro .holo { position: absolute; inset: 0; z-index: 1; background: linear-gradient(115deg, transparent 38%, rgba(255,90,160,.22) 44%, rgba(120,200,255,.28) 50%, rgba(140,255,170,.22) 56%, transparent 62%); }
.ix .hro .duo { position: absolute; inset: 0; width: 100%; height: 100%; object-fit: cover; object-position: 50% 25%; filter: grayscale(1) contrast(1.15); mix-blend-mode: screen; opacity: .45; z-index: 1; }
.ix .hro.h9 { background: #0a2fa8; }
.ix .hro .binder { position: absolute; right: 24px; top: 14px; z-index: 1; display: grid; grid-template-columns: repeat(4, 74px); gap: 8px; }
.ix .hro .binder > div { aspect-ratio: 2.5/3.5; border: 2px solid rgba(255,255,255,.22); background: rgba(255,255,255,.05); overflow: hidden; } .ix .hro .binder img { width: 100%; height: 100%; object-fit: cover; display: block; }
.ix .hro .amb { position: absolute; right: 70px; top: 28px; width: 130px; aspect-ratio: 2.5/3.5; object-fit: cover; z-index: 2; box-shadow: 0 14px 34px rgba(0,0,0,.6); }
.ix .hro .amb2 { position: absolute; right: -60px; top: -80px; width: 460px; aspect-ratio: 2.5/3.5; object-fit: cover; filter: blur(46px) saturate(1.5); opacity: .75; z-index: 1; }
.ix .hro .sky { position: absolute; inset: 0; z-index: 1; } .ix .hro .sky i { position: absolute; background: rgba(255,255,255,.75); border-radius: 50%; } .ix .hro .sky i.g { background: #ffd54a; box-shadow: 0 0 12px 3px rgba(255,213,74,.6); }
.ix .hdr { position: relative; max-width: 760px; height: 130px; border: 3px solid #fff; overflow: hidden; background: #050912; display: flex; flex-direction: column; justify-content: flex-end; padding: 16px 22px; } .ix .hdr .ph { position: absolute; inset: 0; display: flex; opacity: .32; } .ix .hdr .ph img { flex: 1; min-width: 0; object-fit: cover; object-position: 50% 30%; } .ix .hdr:after { content: ''; position: absolute; inset: 0; background: linear-gradient(90deg, #050912 15%, transparent); } .ix .hdr * { position: relative; z-index: 2; } .ix .hdr .ph, .ix .hdr .ph img { position: absolute; } .ix .hdr .ph img { position: relative; } .ix .hdr b { font-size: 46px; line-height: .9; }
.ix .ban { max-width: 560px; border: 3px solid #fff; background: #08153b; position: relative; padding-bottom: 14px; } .ix .ban .cv { height: 110px; overflow: hidden; } .ix .ban .cv img { width: 100%; height: 100%; object-fit: cover; object-position: 50% 30%; opacity: .75; } .ix .ban .av { width: 64px; height: 64px; border-radius: 50%; background: #2f6bff; border: 4px solid #08153b; margin: -32px 0 0 20px; display: flex; align-items: center; justify-content: center; font-size: 28px; } .ix .ban b { display: block; margin: 6px 20px 0; font-size: 30px; } .ix .ban small { margin: 0 20px; opacity: .7; }
.ix .team { max-width: 640px; border: 3px solid #fff; padding: 22px; display: flex; gap: 20px; align-items: center; background: linear-gradient(100deg, #c8102e, #1d428a); position: relative; overflow: hidden; } .ix .team .lg { font-size: 130px; line-height: .8; opacity: .3; } .ix .team b { display: block; font-size: 38px; line-height: .95; margin: 4px 0 10px; } .ix .team .k3t { display: flex; gap: 18px; flex-wrap: wrap; font-size: 12px; } .ix .team .k3t i { font-style: normal; font-size: 24px; display: block; line-height: 1; }
.ix .cover { position: relative; max-width: 640px; height: 170px; border: 3px solid #fff; overflow: hidden; } .ix .cover img { width: 100%; height: 100%; object-fit: cover; object-position: 50% 30%; opacity: .5; } .ix .cover .o { position: absolute; left: 20px; bottom: 16px; } .ix .cover b { display: block; font-size: 40px; line-height: .95; }
.ix .ld { display: flex; flex-direction: column; align-items: center; gap: 10px; padding: 20px; } .ix .ld .m { position: relative; font-size: 90px; line-height: 1; color: rgba(255,255,255,.2) !important; } .ix .ld .m i { position: absolute; left: 0; right: 0; bottom: 0; height: 62%; background: rgba(255,255,255,.9); mix-blend-mode: overlay; }
.ix .tex { max-width: 460px; padding: 24px; border: 3px solid #fff; background-color: #08153b; background-image: repeating-linear-gradient(45deg, rgba(255,255,255,.05) 0 1px, transparent 1px 7px); } .ix .tex b { display: block; font-size: 30px; } .ix .tex span { opacity: .7; font-size: 13px; }
.ix .tkt { position: relative; max-width: 520px; display: flex; align-items: center; gap: 14px; padding: 14px 22px; background: #0a0f20; border: 3px solid #fff; } .ix .tkt:before, .ix .tkt:after { content: ''; position: absolute; top: 50%; width: 22px; height: 22px; border-radius: 50%; background: #08153b; border: 3px solid #fff; transform: translateY(-50%); } .ix .tkt:before { left: -14px; } .ix .tkt:after { right: -14px; } .ix .tkt .side { display: flex; gap: 6px; } .ix .tkt .side img { width: 60px; aspect-ratio: 2.5/3.5; object-fit: cover; } .ix .tkt .mid { font-size: 34px; } .ix .tkt .stamp { position: absolute; right: 26px; bottom: 8px; border: 3px solid #ffd54a; color: #ffd54a !important; padding: 2px 8px; font-size: 16px; transform: rotate(-6deg); }
.ix .setc { display: flex; gap: 14px; align-items: center; max-width: 520px; border: 3px solid #fff; padding: 12px; } .ix .setc .cl { display: grid; grid-template-columns: 1fr 1fr; gap: 3px; width: 92px; flex-shrink: 0; } .ix .setc .cl img, .ix .setc .cl div { width: 100%; aspect-ratio: 2.5/3.5; object-fit: cover; background: rgba(255,255,255,.08); } .ix .setc b { display: block; font-size: 22px; line-height: 1; } .ix .setc .bar { max-width: none; margin: 8px 0 4px; }
/* serie 16 */
.ix .gdens { display: grid; gap: 6px; max-width: 560px; } .ix .gdens img { width: 100%; aspect-ratio: 2.5/3.5; object-fit: cover; display: block; }
.ix .peekw { position: relative; height: 210px; } .ix .peek { position: absolute; left: 60px; top: 20px; width: 300px; display: flex; gap: 12px; padding: 12px; background: #fff; box-shadow: 0 16px 40px rgba(0,0,0,.6); } .ix .peek, .ix .peek * { color: #06122e !important; } .ix .peek img { width: 110px; aspect-ratio: 2.5/3.5; object-fit: cover; } .ix .peek b { display: block; font-size: 22px; line-height: 1; } .ix .peek small { display: block; font-size: 11px; margin: 4px 0 8px; } .ix .peek .gold { font: 800 13px system-ui; }
.ix .sep { max-width: 520px; } .ix .sep .sh { display: flex; align-items: baseline; gap: 12px; padding: 8px 12px; background: #fff; margin: 8px 0; } .ix .sep .sh, .ix .sep .sh * { color: #06122e !important; } .ix .sep .sh b { font-size: 22px; } .ix .sep .sh span { flex: 1; font: 700 12px system-ui; } .ix .sep .sh i { font-style: normal; }
.ix .draw { display: flex; gap: 16px; max-width: 560px; border: 3px solid #fff; padding: 14px; } .ix .draw .dp { flex: 1; min-width: 0; }
.ix .ibar { display: inline-flex; border: 3px solid #fff; } .ix .ibar > div { padding: 10px 18px; text-align: center; border-right: 2px solid rgba(255,255,255,.3); cursor: pointer; } .ix .ibar > div:last-child { border-right: 0; } .ix .ibar b { display: block; font-size: 20px; } .ix .ibar small { font: 800 10px system-ui; letter-spacing: .1em; text-transform: uppercase; } .ix .ibar .red, .ix .ibar .red * { color: #ff6b6f !important; }
.ix .fiche { display: flex; gap: 16px; max-width: 520px; border: 3px solid #fff; padding: 14px; } .ix .fiche .nav { display: flex; gap: 14px; align-items: center; margin-top: 12px; font: 800 12px system-ui; } .ix .fiche .nav span { border: 2px solid rgba(255,255,255,.5); padding: 3px 9px; }
.ix .sil { display: grid; grid-template-columns: repeat(6, 1fr); gap: 8px; max-width: 520px; } .ix .sil > div { aspect-ratio: 2.5/3.5; border: 2px solid rgba(255,255,255,.2); background: rgba(255,255,255,.05); display: flex; align-items: center; justify-content: center; overflow: hidden; } .ix .sil > div.ok { border-color: #fff; } .ix .sil img { width: 100%; height: 100%; object-fit: cover; display: block; } .ix .sil span { font-size: 22px; opacity: .3; }
.ix .stick { max-width: 560px; border: 3px solid #fff; padding: 12px 14px; background: #0a0f20; }
.ix .bal { max-width: 520px; } .ix .scale { position: relative; height: 6px; background: rgba(255,255,255,.2); margin: 14px 0 10px; } .ix .scale:before { content: ''; position: absolute; left: 50%; top: -6px; width: 2px; height: 18px; background: #fff; } .ix .scale i { position: absolute; top: -7px; width: 20px; height: 20px; background: #3ddc97; margin-left: -10px; }
.ix .stampx { display: inline-block; border: 4px solid #3ddc97; padding: 10px 18px; transform: rotate(-3deg); } .ix .stampx, .ix .stampx * { color: #3ddc97 !important; } .ix .stampx b { display: block; font-size: 30px; line-height: 1; } .ix .stampx span { font: 800 11px system-ui; letter-spacing: .1em; text-transform: uppercase; }
.ix .cal { max-width: 360px; border: 3px solid #fff; } .ix .cal .ch { background: #fff; padding: 8px 14px; font-size: 20px; } .ix .cal .ch, .ix .cal .ch * { color: #06122e !important; } .ix .cal .cg { display: grid; grid-template-columns: repeat(7, 1fr); } .ix .cal .cg > div { aspect-ratio: 1; display: flex; align-items: center; justify-content: center; font-size: 13px; border: 1px solid rgba(255,255,255,.1); position: relative; } .ix .cal .cg .ev { background: #ffd54a; } .ix .cal .cg .ev, .ix .cal .cg .ev * { color: #06122e !important; font-weight: 800; } .ix .cal .cg .now { outline: 2px solid #fff; outline-offset: -3px; }
.ix .conf2 { max-width: 440px; border: 3px solid #fff; } .ix .conf2 .f { display: flex; align-items: center; gap: 12px; padding: 10px 14px; border-bottom: 1px solid rgba(255,255,255,.15); } .ix .conf2 .f i { width: 12px; height: 12px; border-radius: 50%; background: #3ddc97; } .ix .conf2 .f.o i { background: #ffb020; } .ix .conf2 .f.r i { background: #ff5a5f; } .ix .conf2 .f.o, .ix .conf2 .f.r { background: rgba(255,176,32,.1); } .ix .conf2 .f span { width: 90px; font: 700 11px system-ui; letter-spacing: .1em; text-transform: uppercase; opacity: .7; } .ix .conf2 .f b { font-size: 15px; }
.ix .help { position: relative; max-width: 420px; } .ix .help i { display: inline-flex; align-items: center; justify-content: center; width: 22px; height: 22px; border: 2px solid #fff; border-radius: 50%; font: 800 13px system-ui; font-style: normal; margin-left: 6px; } .ix .help .hb { margin-top: 10px; padding: 12px 14px; background: #fff; font-size: 13px; line-height: 1.4; } .ix .help .hb, .ix .help .hb * { color: #06122e !important; }
.ix .story { width: 220px; aspect-ratio: 9/16; border: 3px solid #fff; padding: 18px 14px; display: flex; flex-direction: column; align-items: center; gap: 4px; text-align: center; background: linear-gradient(160deg, #050912, #0a2468); } .ix .story .n { font-size: 76px; line-height: .9; } .ix .story .mini { margin: 10px 0; gap: 5px; } .ix .story .mini img { width: 54px; }
/* serie 17 : visualiseur de carte */
.ix .vwd { display: flex; max-width: 860px; height: 380px; border: 3px solid #fff; background: #060b1a; overflow: hidden; }
.ix .vwd .stg { flex: 1.2; position: relative; display: flex; align-items: center; justify-content: center; background: radial-gradient(circle at 50% 45%, #0e2257, #060b1a 70%); min-width: 0; }
.ix .vwd .pn2 { flex: .9; min-width: 0; padding: 18px; border-left: 3px solid #fff; background: #08122b; display: flex; flex-direction: column; gap: 10px; overflow: hidden; }
.ix .vc { height: 78%; aspect-ratio: 2.5/3.5; object-fit: cover; display: block; box-shadow: 0 18px 44px rgba(0,0,0,.6); border-radius: 0; }
.ix .stgc { position: relative; width: 100%; height: 100%; display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 10px; } .ix .stgc .vc { height: 66%; }
.ix .eb { font: 800 11px system-ui; letter-spacing: .18em; text-transform: uppercase; opacity: .75; }
.ix .nm { display: block; font-size: 38px; line-height: .95; }
.ix .tg { display: flex; gap: 6px; flex-wrap: wrap; } .ix .tg span, .ix .bigtags span { padding: 3px 9px; font: 800 12px system-ui; letter-spacing: .1em; } .ix .rc { background: #e67e22; } .ix .au { background: #2e7d32; } .ix .nu { background: #7b1fa2; } .ix .pa { background: #1976d2; }
.ix .bigtags { display: flex; gap: 8px; } .ix .bigtags span { padding: 7px 14px; font-size: 16px; } .ix .tir { font-size: 78px; line-height: .85; color: #ffd54a !important; text-shadow: 0 0 24px rgba(255,213,74,.4); }
.ix .tl4 { display: grid; grid-template-columns: 1fr 1fr; gap: 6px; } .ix .tl4 > div { border: 2px solid rgba(255,255,255,.28); padding: 7px 9px; min-width: 0; } .ix .tl4 small { display: block; font: 800 11px system-ui; letter-spacing: .12em; text-transform: uppercase; opacity: .65; } .ix .tl4 b { font-size: 16px; display: block; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; } .ix .tl4.ico > div { display: grid; grid-template-columns: 22px 1fr; column-gap: 8px; } .ix .tl4.ico i { grid-row: 1 / 3; font-style: normal; font-size: 18px; align-self: center; }
.ix .act { display: flex; gap: 6px; margin-top: auto; } .ix .act span { flex: 1; text-align: center; border: 2px solid #fff; padding: 8px 4px; font: 800 11px system-ui; letter-spacing: .1em; text-transform: uppercase; } .ix .act .p { background: #fff; color: #06122e !important; }
.ix .plq { padding: 8px 18px; background: linear-gradient(180deg, #d9b45a, #a8832f); text-align: center; } .ix .plq, .ix .plq * { color: #2a1d05 !important; } .ix .plq b { display: block; font-size: 20px; } .ix .plq small { font: 700 11px system-ui; letter-spacing: .06em; }
.ix .vb small { font: 800 11px system-ui; letter-spacing: .14em; opacity: .7; } .ix .vb b { display: block; font-size: 52px; line-height: .9; }
.ix .cpy { display: flex; align-items: center; gap: 10px; border: 2px solid rgba(255,255,255,.4); padding: 8px 10px; font-size: 13px; } .ix .cpy span { flex: 1; min-width: 0; }
.ix .three { display: flex; gap: 18px; flex-wrap: wrap; }
.ix .phn { width: 230px; height: 440px; border: 4px solid #fff; background: #060b1a; display: flex; flex-direction: column; overflow: hidden; position: relative; }
.ix .phn .pt { flex: 1; display: flex; align-items: center; justify-content: center; background: radial-gradient(circle at 50% 45%, #0e2257, #060b1a 70%); min-height: 0; position: relative; } .ix .phn .pt .vc { height: 82%; }
.ix .phn .ps { flex: 0 0 auto; background: #08122b; border-top: 3px solid #fff; padding: 8px 12px 12px; display: flex; flex-direction: column; gap: 8px; max-height: 70%; overflow: hidden; }
.ix .grip { width: 40px; height: 4px; background: rgba(255,255,255,.55); margin: 0 auto 2px; }
.ix .fab { display: flex; justify-content: space-around; border-top: 2px solid rgba(255,255,255,.3); padding-top: 8px; font-size: 22px; } .ix .fab .rd { filter: hue-rotate(-30deg); }
.ix .swp { position: relative; width: 100%; height: 100%; display: flex; align-items: center; justify-content: center; gap: 4px; } .ix .swp .ar { font-size: 40px; opacity: .5; } .ix .swp .cnt { position: absolute; top: 8px; left: 50%; transform: translateX(-50%); font: 800 12px system-ui; letter-spacing: .14em; border: 2px solid #fff; padding: 2px 10px; } .ix .swp .vc { height: 70%; }
.ix .dots { display: flex; gap: 6px; justify-content: center; } .ix .dots i { width: 8px; height: 8px; background: rgba(255,255,255,.3); } .ix .dots i.on { background: #fff; }
.ix .rail { display: flex; gap: 6px; } .ix .rail img { width: 36px; aspect-ratio: 2.5/3.5; object-fit: cover; opacity: .55; } .ix .rail img.on { opacity: 1; outline: 2px solid #fff; outline-offset: 2px; }
.ix .stgc.amb { overflow: hidden; } .ix .glow { position: absolute; width: 90%; height: 90%; object-fit: cover; filter: blur(50px) saturate(1.6); opacity: .65; left: 5%; top: 5%; } .ix .stgc.amb .vc { position: relative; z-index: 1; } .ix .refl { position: absolute; bottom: 0; left: 20%; right: 20%; height: 10%; background: radial-gradient(ellipse, rgba(255,255,255,.18), transparent 70%); }
.ix .stgc.vit { background: #03060f; } .ix .stgc.vit .cone { position: absolute; top: 0; width: 70%; height: 100%; background: conic-gradient(from 180deg at 50% 0%, transparent 155deg, rgba(255,235,170,.2) 180deg, transparent 205deg); } .ix .stgc.vit .frm { position: relative; padding: 10px; border: 4px solid #ffd54a; box-shadow: 0 0 0 4px #03060f; } .ix .stgc.vit .vc { height: 230px; box-shadow: none; }
.ix .seg2 { display: flex; border: 3px solid #fff; } .ix .seg2 > div { display: flex; align-items: center; gap: 6px; padding: 4px 10px 4px 4px; font: 800 11px system-ui; letter-spacing: .1em; text-transform: uppercase; cursor: pointer; } .ix .seg2 > div + div { border-left: 2px solid rgba(255,255,255,.4); } .ix .seg2 img { width: 24px; aspect-ratio: 2.5/3.5; object-fit: cover; } .ix .seg2 .on { background: #fff; } .ix .seg2 .on, .ix .seg2 .on * { color: #06122e !important; }
.ix .two2 { display: flex; align-items: center; gap: 10px; height: 80%; } .ix .two2 .vc { height: 100%; } .ix .vs { font-size: 28px; color: #ffd54a !important; }
.ix .cmp > div { display: grid; grid-template-columns: 70px 1fr 1fr; border-bottom: 1px solid rgba(255,255,255,.2); padding: 7px 0; } .ix .cmp small { font: 800 11px system-ui; letter-spacing: .1em; text-transform: uppercase; opacity: .65; } .ix .cmp b { font-size: 16px; } .ix .up { color: #3ddc97 !important; font: 800 12px system-ui; }
.ix .vb2 b { font-size: 70px; line-height: .85; display: block; } .ix .vb2 svg { width: 100%; height: 44px; margin-top: 8px; }
.ix .setp b { font-size: 34px; } .ix .setp .bar { max-width: none; margin: 6px 0; } .ix .setp small { font-size: 12px; opacity: .75; }
.ix .full { width: 100%; height: 100%; display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 8px; } .ix .full .vc { height: 86%; } .ix .full .cap { font-size: 16px; }
`
function Bay({ id, n, title, desc, children }: { id: string; n: string; title: string; desc: string; children: React.ReactNode }) {
  return (
    <section className="bay" id={id}>
      <span className="eyebrow">{n}</span>
      <h2 className="sf">{title}</h2>
      <p className="d">{desc}</p>
      <div className="stage">{children}</div>
    </section>
  )
}

const ALL = [C.mccain, C.edwards, C.maxey, C.hawkins, C.mcw, C.luwawu]
const Tags = () => <div className="tg"><span className="rc">RC</span><span className="au">AUTO</span><span className="nu">/149</span></div>
const Desk = ({ stage, children }: { stage?: React.ReactNode; children: React.ReactNode }) => (
  <div className="vwd wht"><div className="stg">{stage ?? <img className="vc" src={C.mccain.img} alt="" />}</div><div className="pn2">{children}</div></div>
)
const Phone = ({ top, children, h }: { top?: React.ReactNode; children: React.ReactNode; h?: number }) => (
  <div className="phn wht" style={h ? { height: h } : undefined}><div className="pt">{top ?? <img className="vc" src={C.mccain.img} alt="" />}</div><div className="ps">{children}</div></div>
)
const Tiles = () => <div className="tl4">{([['Année', '2024-25'], ['Marque', 'Panini'], ['Collection', 'Contenders'], ['Numéro', '#12']] as [string, string][]).map(t => <div key={t[0]}><small>{t[0]}</small><b>{t[1]}</b></div>)}</div>
const Acts = () => <div className="act"><span className="p">Partager</span><span>Vendre</span><span>Modifier</span></div>

export default function DaIdeas() {
  const [face, setFace] = useState(0)
  const names = ['Panneau à la DA', 'Plaque de musée', 'Tags en en-tête', 'Désignation copiable', 'Tiroir mobile à 3 crans', 'Barre d’actions mobile', 'Swipe et compteur', 'Rail de vignettes', 'Ambiance de scène', 'Mode vitrine', 'Recto / Verso', 'Comparer', 'Valeur en grand', 'Place dans le set', 'Présentation', 'Tuiles d’info']
  return (
    <div className="ix">
      <style>{CSS}</style>
      <Link href="/admin" className="back">← Admin</Link>
      <h1 className="sf">Idées · Série 17 · Visualiseur de carte</h1>
      <p className="lead">Le visualiseur 3D et surtout son panneau d&apos;infos, à la nouvelle DA et pensé d&apos;abord pour le téléphone (tiroir du bas, pouce, lisibilité). Les maquettes montrent l&apos;ordinateur (carte + panneau à droite) et le mobile. Dis-moi les numéros à faire.</p>
      <nav className="tags">{names.map((t, i) => <a key={t} href={`#s${i + 1}`}>{String(i + 1).padStart(2, '0')} {t}</a>)}</nav>

      <Bay id="s1" n="01 — Panneau" title="Un panneau d'infos à la nouvelle DA" desc="Le nom de la carte en Surfquest géant, l'année et la collection en petites capitales au-dessus, les tags RC / AUTO / tirage en gros, puis les infos en 4 tuiles lisibles (libellés 11 px au lieu de 9, valeurs 16 px) et les actions en bas. Cadres à doubles filets, angles droits : le panneau ressemble enfin au reste du site."><Desk><span className="eb">2024-25 · Panini Contenders</span><b className="nm sf">Jared McCain</b><Tags /><Tiles /><Acts /></Desk></Bay>
      <Bay id="s2" n="02 — Scène" title="Une plaque de musée sous la carte" desc="Sous la carte en 3D, un cartouche en laiton comme dans un musée : nom, année, collection, numéro. L'essentiel est lu sans ouvrir le panneau, qui ne garde que les actions et la valeur. Sur mobile, la plaque remplace l'ancien bandeau d'infos réduit."><Desk stage={<div className="stgc"><img className="vc" src={C.maxey.img} alt="" /><div className="plq"><b className="sf">Tyrese Maxey</b><small>2020-21 Court Kings · #12 · /149</small></div></div>}><span className="eb">Actions</span><Acts /><div className="vb"><small>VALEUR</small><b className="sf">38 €</b></div></Desk></Bay>
      <Bay id="s3" n="03 — Panneau" title="Les tags et le tirage en grand, tout en haut" desc="RC, AUTO, PATCH et NUM deviennent de vraies étiquettes bien visibles en tête du panneau, avec le tirage « /149 » en doré énorme (l'info que cherchent les collectionneurs). Plus besoin de chercher le numéro dans la liste."><Desk><div className="bigtags"><span className="rc">RC</span><span className="au">AUTO</span><span className="pa">PATCH</span></div><div className="tir sf">/149</div><span className="eb">Exemplaire 87 sur 149</span><Tiles /></Desk></Bay>
      <Bay id="s4" n="04 — Panneau" title="La désignation complète à copier en un clic" desc="Une ligne propre « 2024-25 Panini Contenders #12 RC /149 » avec un bouton Copier. Pratique pour annoncer une vente, chercher sur eBay ou écrire à un collectionneur. La désignation Beckett est déjà construite pour le référencement : on la réutilise."><Desk><span className="eb">Désignation</span><div className="cpy"><span>2024-25 Panini Contenders #12 RC /149</span><button className="btn" style={{ padding: '4px 10px' }}>Copier</button></div><span className="eb" style={{ marginTop: 14 }}>Chercher</span><div className="sv"><span>eBay</span><span>130point</span><span>Vinted</span></div></Desk></Bay>
      <Bay id="s5" n="05 — Mobile" title="Un tiroir à trois crans sur téléphone" desc="Aujourd'hui le panneau est soit minuscule (22 %) soit plein écran. Trois crans : réduit (nom + tirage + valeur), moyen (la moitié, les tuiles d'info) et plein (tout, avec défilement). On tire sur la poignée et il s'accroche au cran le plus proche. La carte reste visible aux deux premiers crans."><div className="three"><Phone><div className="grip" /><b className="nm sf" style={{ fontSize: 20 }}>Jared McCain</b><Tags /></Phone><Phone><div className="grip" /><b className="nm sf" style={{ fontSize: 20 }}>Jared McCain</b><Tags /><Tiles /></Phone><Phone top={<span className="sm">Carte masquée</span>}><div className="grip" /><b className="nm sf" style={{ fontSize: 20 }}>Jared McCain</b><Tags /><Tiles /><Acts /></Phone></div></Bay>
      <Bay id="s6" n="06 — Mobile" title="Une barre d'actions fixe en bas, sous le pouce" desc="Partager, Vendre, Modifier, Supprimer et Valeur en icônes dans une barre fixe collée en bas de l'écran, toujours accessible, quel que soit le cran du tiroir. Les gros boutons empilés disparaissent, et tout se fait d'une main."><div className="three"><Phone h={400}><div className="grip" /><b className="nm sf" style={{ fontSize: 20 }}>Jared McCain</b><Tags /><div className="fab"><span>🔗</span><span>🏷</span><span>✏️</span><span>💶</span><span className="rd">🗑</span></div></Phone></div></Bay>
      <Bay id="s7" n="07 — Mobile" title="Glisser pour changer de carte, avec un compteur" desc="Un balayage gauche / droite passe à la carte suivante ou précédente de la galerie, avec « 12 / 599 » en haut et de petits points. Aujourd'hui les flèches suivant / précédent sont peu pratiques au pouce. Un léger retour haptique à chaque carte."><div className="three"><Phone h={400} top={<div className="swp"><span className="cnt">12 / 599</span><span className="ar">‹</span><img className="vc" src={C.mccain.img} alt="" /><span className="ar">›</span></div>}><div className="grip" /><b className="nm sf" style={{ fontSize: 20 }}>Jared McCain</b><div className="dots"><i /><i className="on" /><i /><i /><i /></div></Phone></div></Bay>
      <Bay id="s8" n="08 — Ordinateur" title="Un rail de vignettes pour naviguer vite" desc="Sous la carte, une rangée de miniatures des cartes voisines de la galerie : un clic change de carte, la courante est entourée de blanc. Parcourir une collection sans fermer le visualiseur à chaque fois. Se replie sur mobile."><Desk stage={<div className="stgc"><img className="vc" src={C.edwards.img} alt="" /><div className="rail">{[...ALL, C.mccain].map((c, i) => <img key={i} src={c.img} alt="" className={i === 2 ? 'on' : ''} />)}</div></div>}><span className="eb">Anthony Edwards</span><Tiles /></Desk></Bay>
      <Bay id="s9" n="09 — Scène" title="Une ambiance qui prend les couleurs de la carte" desc="Le fond du visualiseur reçoit une lueur floue tirée de l'image de la carte (bleu pour une carte bleue, rouge pour une rouge), plus un reflet léger au sol. Chaque carte a sa propre ambiance, sans aucun mouvement. Se désactive en mode économie d'énergie."><Desk stage={<div className="stgc amb"><img className="glow" src={C.mccain.img} alt="" /><img className="vc" src={C.mccain.img} alt="" /><div className="refl" /></div>}><span className="eb">Ambiance</span><b className="nm sf">Jared McCain</b><Tiles /></Desk></Bay>
      <Bay id="s10" n="10 — Scène" title="Un mode vitrine : cadre et projecteur" desc="Un bouton « Vitrine » met la carte dans un cadre doré sous un cône de lumière, comme au Grail Wall, avec un fond sombre uni. Pour les cartes phares et pour les captures d'écran partagées. La carte garde ses coins nets."><Desk stage={<div className="stgc vit"><div className="cone" /><div className="frm"><img className="vc" src={C.maxey.img} alt="" /></div></div>}><span className="eb">Mode vitrine</span><b className="nm sf">Tyrese Maxey</b><span className="sm">Carte phare n°1</span></Desk></Bay>
      <Bay id="s11" n="11 — Scène" title="Un commutateur Recto / Verso avec les deux miniatures" desc="Sous la carte, un commutateur carré Recto | Verso avec la miniature de chaque face. Le retournement se fait d'un clic net (et reste possible par glissement). Aujourd'hui on ne sait pas toujours qu'il y a un verso à voir."><Desk stage={<div className="stgc"><img className="vc" src={face ? C.edwards.img : C.mccain.img} alt="" /><div className="seg2"><div className={face === 0 ? 'on' : ''} onClick={() => setFace(0)}><img src={C.mccain.img} alt="" />Recto</div><div className={face === 1 ? 'on' : ''} onClick={() => setFace(1)}><img src={C.edwards.img} alt="" />Verso</div></div></div>}><span className="eb">Faces</span><Tiles /></Desk></Bay>
      <Bay id="s12" n="12 — Panneau" title="Comparer avec une autre carte" desc="Un bouton « Comparer » ouvre une deuxième carte à côté (choisie dans ta galerie ou celle d'un ami) et un petit tableau des écarts : année, tirage, valeur. Utile avant un échange ou pour choisir quoi garder."><Desk stage={<div className="stgc"><div className="two2"><img className="vc" src={C.mccain.img} alt="" /><b className="vs sf">VS</b><img className="vc" src={C.maxey.img} alt="" /></div></div>}><span className="eb">Comparaison</span><div className="cmp"><div><small>Tirage</small><b>/149</b><b>/99</b></div><div><small>Valeur</small><b>45 €</b><b className="up">38 €</b></div></div></Desk></Bay>
      <Bay id="s13" n="13 — Panneau" title="La valeur en grand avec sa petite courbe" desc="Un bloc valeur bien visible : le montant en très gros, l'écart sur 30 jours et une mini-courbe, avec « Modifier la valeur » en lien discret. La valeur est l'info la plus regardée, elle est aujourd'hui noyée dans la liste."><Desk><span className="eb">Valeur estimée</span><div className="vb2"><b className="sf">45 €</b><span className="up">▲ +4 € sur 30 jours</span><svg viewBox="0 0 160 40" preserveAspectRatio="none"><polyline points="0,32 25,28 50,30 75,20 100,22 130,10 160,6" fill="none" stroke="#3ddc97" strokeWidth="3" /></svg></div><span className="sm">Modifier la valeur</span></Desk></Bay>
      <Bay id="s14" n="14 — Panneau" title="La place de la carte dans son set" desc="Un bloc « #12 sur 300 · 2024-25 Contenders » avec la jauge de ta progression sur ce set (« 288 / 300 ») et « prochaine manquante : #213 ». On passe de la carte à son objectif de complétion sans quitter le visualiseur."><Desk><span className="eb">Dans le set</span><div className="setp"><b className="sf">#12 / 300</b><div className="bar"><i style={{ width: '96%' }} /></div><small>288 / 300 · prochaine manquante : #213</small></div></Desk></Bay>
      <Bay id="s15" n="15 — Mode" title="Un mode présentation plein écran" desc="Un bouton cache tout le panneau : il ne reste que la carte, très grande, avec son nom en légende et un petit « Afficher les infos ». Pour montrer une carte à quelqu'un au salon, ou sur un écran. Sur mobile, la carte occupe tout l'écran."><div className="three"><Phone h={400} top={<div className="full"><img className="vc" src={C.maxey.img} alt="" /><span className="cap sf">Tyrese Maxey</span></div>}><button className="btn o" style={{ padding: '5px 12px' }}>Afficher les infos</button></Phone></div></Bay>
      <Bay id="s16" n="16 — Panneau" title="Des tuiles d'info avec icônes, lisibles du premier coup" desc="Année, marque, collection, numéro, variation, signature : chacune dans une tuile à filet fin avec une petite icône, sur 2 colonnes (1 sur très petit écran). Fini la liste de libellés de 9 px serrés ; chaque info a sa place et on la repère."><Desk><span className="eb">Détails</span><div className="tl4 ico">{([['📅', 'Année', '2024-25'], ['🏷', 'Marque', 'Panini'], ['📦', 'Collection', 'Contenders'], ['#', 'Numéro', '12'], ['✨', 'Variation', 'Prizm Silver'], ['✍️', 'Signée par', 'J. McCain']] as [string, string, string][]).map(t => <div key={t[1]}><i>{t[0]}</i><small>{t[1]}</small><b>{t[2]}</b></div>)}</div></Desk></Bay>
    </div>
  )
}
